### ISSUE TITLE
Coverage is too low

### ISSUE THREAD

**Issue by llorllale** [llorllale/cactoos-matchers#1]
Need to un-comment the jacoco configurations in the POM and make the following errors go away:

```
--- jacoco-maven-plugin:0.7.7.201606060606:check (jacoco-check) @ cactoos-matchers ---
Loading execution data file C:\dev\cactoos-matchers\target\jacoco.exec
Analyzed bundle 'cactoos-matchers' with 7 classes
Rule violated for bundle cactoos-matchers: instructions covered ratio is 0.00, but expected minimum is 0.61
Rule violated for bundle cactoos-matchers: lines covered ratio is 0.00, but expected minimum is 0.65
Rule violated for bundle cactoos-matchers: branches covered ratio is 0.00, but expected minimum is 0.65
Rule violated for bundle cactoos-matchers: complexity covered ratio is 0.00, but expected minimum is 0.57
Rule violated for bundle cactoos-matchers: methods covered ratio is 0.00, but expected minimum is 0.57
```

For starters, the CodeCov report from cactoos can be found [here](https://codecov.io/gh/yegor256/cactoos/tree/master/src/main/java/org/cactoos/matchers).

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@rultor release, tag is `0.0.1`

**Comment by llorllale** [comment]
@0crat hey

**Comment by 0crat** [comment]
> @0crat hey ([here](https://github.com/llorllale/cactoos-matchers/issues/1#issuecomment-388557591))

@llorllale Hey, what's up, how is it going?

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/1#issuecomment-388576358))

@llorllale Job [#1](https://github.com/llorllale/cactoos-matchers/issues/1) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#1](https://github.com/llorllale/cactoos-matchers/issues/1) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/1361513210); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by SharplEr** [comment]
@0crat waiting
Waiting for reviewer for #15

**Comment by 0crat** [comment]
> @0crat waiting Waiting for reviewer for #15  ([here](https://github.com/llorllale/cactoos-matchers/issues/1#issuecomment-392269271))

@SharplEr The impediment for [#1](https://github.com/llorllale/cactoos-matchers/issues/1) was registered successfully by @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by SharplEr** [comment]
@llorllale  PR #15  was merged, please close the issue.

**Comment by llorllale** [comment]
@SharplEr thanks

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1](https://github.com/llorllale/cactoos-matchers/issues/1) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
