### ISSUE TITLE
Upgrade qulice to 0.17.3

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#10]
Shamelessly copied from yegor256/cactoos-http#49 :)

New qulice version brings following important changes:
- removal of `@author` tag (it is prohibited now)
- removal of `@version` tag (it is prohibited now)
- license header should start with `/*` instead of `/**` - this will fix problem with IntelliJ reporting it as a javadoc that is not attached to any class
- checkstyle validation performance improvement (speedup of ~ 10%)
- And few minor formatting changes.

Please upgrade the qulice and fix the new problems found.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/10#issuecomment-390406355))

@llorllale Job [#10](https://github.com/llorllale/cactoos-matchers/issues/10) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#10](https://github.com/llorllale/cactoos-matchers/issues/10) assigned to @jsoroka[/z](https://www.0crat.com/u/jsoroka), here is [why](https://www.0crat.com/footprint/C63314D6Z/1800642593); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by jsoroka** [comment]
Does "checkstyle validation performance improvement" in the description ("copied from yegor256/cactoos-http#49") imply removing [this line](https://github.com/llorllale/cactoos-matchers/blob/master/pom.xml#L106) as was the analogous case in the associated PR yegor256/cactoos-http#55 as seen [here](https://github.com/yegor256/cactoos-http/pull/55/commits/852762c8c647b67b2224c0d149cb9bca254d34e3#diff-600376dffeb79835ede4a0b285078036L164)?

**Comment by victornoel** [comment]
@jsoroka I agree with your conclusion (also, don't forget to address your comment to someone so that there is no ambiguity, cf http://www.zerocracy.com/policy.html#42 :)

**Comment by 0crat** [comment]
@jsoroka[/z](https://www.0crat.com/u/jsoroka) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by jsoroka** [comment]
@victornoel Thank you for the pointer.  Please close the issue now, if appropriate.  I do not see a way to close it myself.

**Comment by victornoel** [comment]
@jsoroka yes, it is normal, I have to do it :) thanks!

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @jsoroka[/z](https://www.0crat.com/u/jsoroka), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#10](https://github.com/llorllale/cactoos-matchers/issues/10) is now out of scope

**Comment by elenavolokhova** [comment]
@jsoroka According to our [Policy](http://www.zerocracy.com/policy.html#42):
> Messages in a job always start with a name of a user they are addressed to;

I see, that you've been told about this, but I can not give 'good' mark here, because some of your messages are still not addressed. If you have same issue in currently opened tickets, please, edit you comments and address all of them to be able to receive bonus for good quality :) Thanks!

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @jsoroka[/z](https://www.0crat.com/u/jsoroka)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
