### ISSUE TITLE
Add new ctor(s) to Assertion in order to simplify the code within the unit tests

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#102]
1. Sometimes no need to create a scalar for the assertion for like
    ```java
    @Test
    public void sum(){
      new Assertion<>(
           "the sum is <4>",
            2 + 2,
            new IsEqual<>(4)
      ).affirm();
    }
    ```
2. Moreover, we can also add a new ctor for equality checks:
    ```java
    @Test
    public void sum(){
        new Assertion<>(
             "the sum is <4>",
              2 + 2,
              4
        ).affirm();
    }
    ```
    with text this might be more laconic
    ```java
    @Test
    public void sum(){
        new Assertion<>(
             "the text is 'The Story'",
              new FormattedText("%s %s", "The", "Story"),
              new TextOf("The Story")
        ).affirm();
    }
    ```
    where the `TextOf` will be wrapped to `new IsEqual<>` under the hood.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup it's not possible I'm afraid:
* adding a ctor with the `test` as a non-scalar confuses the compiler when passing in scalars: are you trying to call `Assertion(String, Scalar<T>, Matcher<T>)` or are you calling `Assertion(String, T, Matcher<T>)`?
* same thing happens with the other arg

**Comment by victornoel** [comment]
@llorllale maybe this issue can be rediscussed now that we started to introduce `Assertion2`?

**Comment by llorllale** [comment]
@victornoel @dgroup yes, turns out that we can simplify the Assertion API to accept the value directly (ie no scalar) when testing values, as well as accepting Scalars for tests with `Throws`.

See #111

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#102` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
