### ISSUE TITLE
Update to latest cactoos and remove usage of deprecated UncheckedScalar

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#103]
`UncheckedScalar` has been marked deprecated and for it to be removed, we must first remove its usage in cactoos-matchers, make a release and then update cactoos to latest cactoos-matchers (while removing the deprecated class at the same time).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by llorllale** [comment]
@victornoel ugh, what a headache...

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/103#issuecomment-480093048))

@llorllale Job [#103](https://github.com/llorllale/cactoos-matchers/issues/103) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@llorllale if you want you can assign me this one, I just got assigned the related job in cactoos: yegor256/cactoos#1086

**Comment by 0crat** [comment]
The job [#103](https://github.com/llorllale/cactoos-matchers/issues/103) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/696ed21f-a665-4cd2-a03a-71835dd37025); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/103#issuecomment-493781160))

@Umbrah The user @umbrah[/z](https://www.0crat.com/u/umbrah) resigned from [#103](https://github.com/llorllale/cactoos-matchers/issues/103), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0crat** [comment]
The job [#103](https://github.com/llorllale/cactoos-matchers/issues/103) assigned to @scristalli[/z](https://www.0crat.com/u/scristalli), here is [why](https://www.0crat.com/footprint/C63314D6Z/d0a44fd2-9c40-4ce5-ad85-931a90c186ad); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by scristalli** [comment]
@0crat waiting for pull request #125 to be reviewed

**Comment by 0crat** [comment]
> @0crat waiting for pull request #125 to be reviewed ([here](https://github.com/llorllale/cactoos-matchers/issues/103#issuecomment-495908125))

@scristalli The impediment for [#103](https://github.com/llorllale/cactoos-matchers/issues/103) was registered successfully by @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by scristalli** [comment]
@llorllale can we please make a release now? Afterwards, I think I can close this.

**Comment by victornoel** [comment]
@llorllale yes I second this, I need it for some issues in cactoos :)

**Comment by llorllale** [comment]
@victornoel @scristalli [release in progress](https://github.com/llorllale/cactoos-matchers/pull/125#issuecomment-499912889)

**Comment by llorllale** [comment]
@scristalli btw, it's best practice to reference the issue from the PR (so that we'd see the link to the PR in the issue)

**Comment by scristalli** [comment]
@llorllale noted, thanks. I will make sure I do it in the next PRs.

**Comment by scristalli** [comment]
@victornoel can we close this? I think the job is finished for what concerns cactoos-matchers.

**Comment by victornoel** [comment]
@scristalli yep, thanks!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @scristalli[/z](https://www.0crat.com/u/scristalli), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#103](https://github.com/llorllale/cactoos-matchers/issues/103) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)
