### ISSUE TITLE
Allow Throws to match by a part of an exception message 

### ISSUE THREAD

**Issue by atapin** [llorllale/cactoos-matchers#108]
Currently, `Throws` doesn't allow to match exception messages that are dynamic and out of the caller's control. E.g.:
```
AssertionError: Must throw exception
Expected: Exception has type 'java.lang.IllegalStateException' and message ''Item #2 of org.cactoos.iterator.Immutable is NULL'
     but: Exception has type 'java.lang.IllegalStateException' and message 'Item #2 of org.cactoos.iterator.Immutable@6d86b085 is NULL'
```
This behavior blocks replacing `@Rule` with `Throws` matcher in `org.cactoos.iterator.NoNullsTest#nthThrowsErrorIfNull` ([see](https://github.com/yegor256/cactoos/blob/master/src/test/java/org/cactoos/iterator/NoNullsTest.java))

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@atapin I guess we can have `Throws` accept a `Func<String, Boolean>` for this

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/108#issuecomment-482757461))

@llorllale Job [#108](https://github.com/llorllale/cactoos-matchers/issues/108) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @atapin[/z](https://www.0crat.com/u/atapin)

**Comment by atapin** [comment]
@llorllale does it make sense to inherit `Throws` from `TextMatcherEnvelope`?

**Comment by llorllale** [comment]
@atapin `TextMatcherEnvelope` is a matcher of `Text`; `Throws` can match anything. If `Throws` were to extend `TextMatcherEnvelope`, it would only be useful for testing exceptions thrown from operations that return `Text`. We want `Throws` to be useful for any generic operation.

**Comment by 0crat** [comment]
The job [#108](https://github.com/llorllale/cactoos-matchers/issues/108) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/8967c2d7-c594-44bf-8e56-45f4e87f40d2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/108#issuecomment-490508542))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#108](https://github.com/llorllale/cactoos-matchers/issues/108), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#108](https://github.com/llorllale/cactoos-matchers/issues/108) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C63314D6Z/7da207e4-4a15-492c-9174-db6f6dc1e06b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat Please wait for https://github.com/llorllale/cactoos-matchers/pull/123 to be merged.

**Comment by 0crat** [comment]
> @0crat Please wait for https://github.com/llorllale/cactoos-matchers/pull/123 to be merged. ([here](https://github.com/llorllale/cactoos-matchers/issues/108#issuecomment-491605138))

@vzurauskas Can't understand "Please", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by vzurauskas** [comment]
@0crat Wait for https://github.com/llorllale/cactoos-matchers/pull/123 to be merged. :)

**Comment by 0crat** [comment]
> @0crat Wait for https://github.com/llorllale/cactoos-matchers/pull/123 to be merged. :) ([here](https://github.com/llorllale/cactoos-matchers/issues/108#issuecomment-491605307))

@vzurauskas The impediment for [#108](https://github.com/llorllale/cactoos-matchers/issues/108) was registered successfully by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by vzurauskas** [comment]
@llorllale I think https://github.com/llorllale/cactoos-matchers/pull/126 solved this issue. Can it be closed?

**Comment by vzurauskas** [comment]
@llorllale Also, could you release a new version? It's needed for https://github.com/yegor256/cactoos/issues/1106

**Comment by llorllale** [comment]
@vzurauskas ask the ticket's reporter if it can be closed

**Comment by llorllale** [comment]
@vzurauskas [release in progress](https://github.com/llorllale/cactoos-matchers/pull/126#issuecomment-497975854)

**Comment by vzurauskas** [comment]
@atapin I think https://github.com/llorllale/cactoos-matchers/pull/126 solved this issue. Can it be closed?

**Comment by atapin** [comment]
@vzurauskas you are right. Closing.

**Comment by 0crat** [comment]
Job [#108](https://github.com/llorllale/cactoos-matchers/issues/108) is not in the agenda of @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#108](https://github.com/llorllale/cactoos-matchers/issues/108) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)
