### ISSUE TITLE
cactoos-matchers depends on cactoos which contains the matchers!

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#11]
There is two thing really strange:
1. cactoos-matchers relies on an old version of cactoos that currently contains the very same matchers
2. if cactoos-matchers were relying on a newer version of cactoos, the latter would rely on cactoos-matchers: this is not very good architecturally speaking!

This should be fixed, I don't know how.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@victornoel transition away from cactoos is not yet complete:

* Will upgrade dependency version on `cactoos` to a more recent one that does not have the matchers
* Will update `cactoos-matchers` version on cactoos once the previous is done
* Some matchers still to be migrated - see #17

**Comment by victornoel** [comment]
@llorllale my main worry is the cyclic dependency between cactoos-matchers and cactoos, this can't be good.

**Comment by llorllale** [comment]
@victornoel to be honest, it *does* sort of raise a faint bell in my head... but at this moment I can't think of a concrete scenario where it is a real issue.

**Comment by victornoel** [comment]
@llorllale you are the ARC, as long as you are aware of the issue, it's good for me :)
Should I close this issue?

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
