### ISSUE TITLE
Assertion2.java:67-69: Phase out the original Assertion...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#110]
The puzzle `88-bbf98b56` from #88 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/b6e2e5687dce498db867d62655b2df62025dd4a1/src/main/java/org/llorllale/cactoos/matchers/Assertion2.java#L67-L69

The puzzle was created by @llorllale on 18-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by llorllale** [comment]
@0crat assign me

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/llorllale/cactoos-matchers/issues/110#issuecomment-485248969))

@llorllale The job [#110](https://github.com/llorllale/cactoos-matchers/issues/110) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/e1436171-3b5f-43b3-8f13-1949a6eaed01); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@0crat wait I submitted PR #111 for this

**Comment by 0crat** [comment]
> @0crat wait I submitted PR #111 for this ([here](https://github.com/llorllale/cactoos-matchers/issues/110#issuecomment-485255722))

@llorllale The impediment for [#110](https://github.com/llorllale/cactoos-matchers/issues/110) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `88-bbf98b56` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#113](https://github.com/llorllale/cactoos-matchers/issues/113) is still not solved.

**Comment by 0crat** [comment]
The job [#110](https://github.com/llorllale/cactoos-matchers/issues/110) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#116](https://github.com/llorllale/cactoos-matchers/issues/116) is still not solved; solved: [#113](https://github.com/llorllale/cactoos-matchers/issues/113).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#113](https://github.com/llorllale/cactoos-matchers/issues/113), [#116](https://github.com/llorllale/cactoos-matchers/issues/116).
