### ISSUE TITLE
Update maven-compiler-plugin and fix bug on it to allow incremental compilation

### ISSUE THREAD

**Issue by fabriciofx** [llorllale/cactoos-matchers#112]
Let's update `maven-compiler-plugin` to `3.8.0` version and fix a bug in this plugin which doesn't allow incremental compilation that increase compile and running time. To fix both we need change `pom.xml` to:
```
<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.8.0</version>
  <configuration>
    <source>1.8</source>
    <target>1.8</target>
    <useIncrementalCompilation>false</useIncrementalCompilation>
  </configuration>
</plugin>
```
Please, pay attention to `<version>` and `<useIncrementalCompilation>` tag.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by victornoel** [comment]
@fabriciofx the objective is is to disable incremental compilation? Why do we want to do that? I see the other cactoos projects have this kind of setup, I don't understand why exactly, do you know?

**Comment by fabriciofx** [comment]
@victornoel I opened this issue a lot of time ago. It's because there is (or was) a bug in `maven-compiler-plugin`. I think this bug already was fixed. So, I'll close it, ok?

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#112` is not assigned, can't get performer

**Comment by victornoel** [comment]
@fabriciofx ok, thank you, I removed the option in https://github.com/yegor256/cactoos/pull/1412 for cactoos (I will do cactoos-matchers later) so we will see what happens without it :)
