### ISSUE TITLE
HasEntryTest.java:38-41: Add two more tests for the...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#114]
The puzzle `65-01fd6042` from #65 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/5bfb891b2badafbf62533e68d150e3755fd1c24a/src/test/java/org/llorllale/cactoos/matchers/HasEntryTest.java#L38-L41

The puzzle was created by @rultor on 25-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#114](https://github.com/llorllale/cactoos-matchers/issues/114) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#114](https://github.com/llorllale/cactoos-matchers/issues/114) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/3f0c71c4-70b2-47c9-b27c-411ada591754); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat waiting for #106

**Comment by 0crat** [comment]
> @0crat waiting for #106  ([here](https://github.com/llorllale/cactoos-matchers/issues/114#issuecomment-495922637))

@victornoel The impediment for [#114](https://github.com/llorllale/cactoos-matchers/issues/114) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@0crat wait for #140 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #140 to be merged ([here](https://github.com/llorllale/cactoos-matchers/issues/114#issuecomment-513564740))

@victornoel Job [#114](https://github.com/llorllale/cactoos-matchers/issues/114) is already on hold

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0pdd** [comment]
The puzzle `65-01fd6042` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) all `QA`s are on vacation. Please handle that.

**Comment by 0crat** [comment]
The job [#114](https://github.com/llorllale/cactoos-matchers/issues/114) is now out of scope

**Comment by victornoel** [comment]
@paulodamaso could you assert quality please?

**Comment by paulodamaso** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/llorllale/cactoos-matchers/issues/114#issuecomment-531895806))

@paulodamaso There is no quality review for [#114](https://github.com/llorllale/cactoos-matchers/issues/114), no performer

**Comment by paulodamaso** [comment]
@0crat pay 35min @victornoel

**Comment by 0crat** [comment]
> @0crat pay 35min @victornoel  ([here](https://github.com/llorllale/cactoos-matchers/issues/114#issuecomment-534547112))

@paulodamaso The user @victornoel[/z](https://www.0crat.com/u/victornoel) works for free in this project, see [§49](http://www.zerocracy.com/policy.html#49)

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/llorllale/cactoos-matchers/issues/114#issuecomment-534558452); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by victornoel** [comment]
@paulodamaso yeah... let's forget about it :) thx anyway
