### ISSUE TITLE
Assertion2.java:67-69: Delete the original Assertion and...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#116]
The puzzle `113-840654f6` from #113 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/906401c2f9ac1cb38cb8b6bf2cc1a5b579eb8d52/src/main/java/org/llorllale/cactoos/matchers/Assertion2.java#L67-L69

The puzzle was created by @llorllale on 25-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Job [#116](https://github.com/llorllale/cactoos-matchers/issues/116) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/llorllale/cactoos-matchers/issues/116#issuecomment-487026857))

@llorllale The job [#116](https://github.com/llorllale/cactoos-matchers/issues/116) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/007a1089-86cf-4285-94a4-4f4f48f9cd3c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat wait because I submitted PR #117 for this

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
> @0crat wait because I submitted PR #117 for this ([here](https://github.com/llorllale/cactoos-matchers/issues/116#issuecomment-487029339))

@llorllale The impediment for [#116](https://github.com/llorllale/cactoos-matchers/issues/116) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `113-840654f6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 11 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#116](https://github.com/llorllale/cactoos-matchers/issues/116) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)
