### ISSUE TITLE
Throws do not support null as message

### ISSUE THREAD

**Issue by Umbrah** [llorllale/cactoos-matchers#119]
I want to verify NullPointerException is thrown, but org.llorllale.cactoos.matchers.Throws fails when I use null as msg parameter. I want to be able to use it or have another constructor only with exception param.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by ilyakharlamov** [comment]
Unit test example: `

    @test
    public void nullMessageTest(){
        final Description description = new StringDescription();
        new Throws<>(null, NullPointerException.class).matchesSafely(
            () -> {
                final Object obj = null;
                return obj.getClass();
            },
            description
        );
    }`

**Comment by llorllale** [comment]
@0crat in

**Comment by llorllale** [comment]
@Umbrah let's add a ctor that takes in just the exception type

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/119#issuecomment-487785387))

@llorllale Job [#119](https://github.com/llorllale/cactoos-matchers/issues/119) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0crat** [comment]
The job [#119](https://github.com/llorllale/cactoos-matchers/issues/119) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/33da1e12-101e-462b-b497-ae52348c3ea8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #126 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #126 to be merged ([here](https://github.com/llorllale/cactoos-matchers/issues/119#issuecomment-497366130))

@victornoel The impediment for [#119](https://github.com/llorllale/cactoos-matchers/issues/119) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@Umbrah this has been fixed in #126, the issue can now be closed :)

**Comment by victornoel** [comment]
@llorllale the reporter does not seem to answer, can we close this?

**Comment by victornoel** [comment]
@llorllale @Umbrah ping

**Comment by llorllale** [comment]
@umbrah closing due to unresponsiveness (PR #126 merged for this)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#119](https://github.com/llorllale/cactoos-matchers/issues/119) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
The job [#119](https://github.com/llorllale/cactoos-matchers/issues/119) is now out of scope

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/119#issuecomment-499821676))

@g4s8 This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#119](https://github.com/llorllale/cactoos-matchers/issues/119) is not in scope
  * The job is waiting quality review verdict by @sereshqua[/z](https://www.0crat.com/u/sereshqua) for 7hr
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23119%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by sereshqua** [comment]
@ilyakharlamov can you please edit your [comment](https://github.com/llorllale/cactoos-matchers/issues/119#issuecomment-487753522)  that it start with the user'w name it is referred to? otherwise quality is acceptable here

**Comment by victornoel** [comment]
@sereshqua I don't think @ilyakharlamov is here anymore with us.

**Comment by sereshqua** [comment]
@victornoel, yeap, just a matter of policy, so issue performer knows why quality is not good

**Comment by victornoel** [comment]
@sereshqua I understand, but you never told 0crat about the quality in the end ;)

**Comment by sereshqua** [comment]
@0pdd quality acceptable

**Comment by 0pdd** [comment]
> @0pdd quality acceptable 

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by g4s8** [comment]
@0crat status
