### ISSUE TITLE
the test in cactoos-matchers are testing the matchers in old cactoos

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#12]
The tests in cactoos-matchers are in the package `org.cactoos.matchers` and do not refer to the classes in `org.llorllale.cactoos.matchers`, so they are effectively testing the matchers from cactoos (which is an old version, see #11).

The tests should be ported to the new matchers.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#12](https://github.com/llorllale/cactoos-matchers/issues/12) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/12#issuecomment-390422129))

@llorllale Job [#12](https://github.com/llorllale/cactoos-matchers/issues/12) is already in scope

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#12](https://github.com/llorllale/cactoos-matchers/issues/12) assigned to @jonathanihm[/z](https://www.0crat.com/u/jonathanihm), here is [why](https://www.0crat.com/footprint/C63314D6Z/1810156683); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@jonathanihm[/z](https://www.0crat.com/u/jonathanihm) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @jonathanihm[/z](https://www.0crat.com/u/jonathanihm) resigned from [#12](https://github.com/llorllale/cactoos-matchers/issues/12), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#12` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#12` is not assigned, can't get performer

**Comment by dgroup** [comment]
@llorllale is it still actual? 
I couldn't understand the scope here.

**Comment by llorllale** [comment]
@dgroup looks like you're right.

@victornoel can we close this?

**Comment by victornoel** [comment]
@llorllale @dgroup yes indeed, it has been fixed apparently :)

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#12` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#12](https://github.com/llorllale/cactoos-matchers/issues/12) is now out of scope
