### ISSUE TITLE
MatcherEnvelope.java:47-50: Write unit tests for...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#121]
The puzzle `94-45419d52` from #94 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/7fff8ac12133234d8c36c22a58bf6733956d1af0/src/main/java/org/llorllale/cactoos/matchers/MatcherEnvelope.java#L47-L50

The puzzle was created by @vzurauskas on 28-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#121](https://github.com/llorllale/cactoos-matchers/issues/121) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#121](https://github.com/llorllale/cactoos-matchers/issues/121) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/ff191eaf-6981-4639-ab5c-6a0070f22541); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse  ([here](https://github.com/llorllale/cactoos-matchers/issues/121#issuecomment-497955674))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#121](https://github.com/llorllale/cactoos-matchers/issues/121), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#121](https://github.com/llorllale/cactoos-matchers/issues/121) assigned to @scristalli[/z](https://www.0crat.com/u/scristalli), here is [why](https://www.0crat.com/footprint/C63314D6Z/ba0f4f5c-641f-4436-a8d0-c024f293af20); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by scristalli** [comment]
@0crat waiting for #130 to be reviewed

**Comment by 0crat** [comment]
> @0crat waiting for #130 to be reviewed ([here](https://github.com/llorllale/cactoos-matchers/issues/121#issuecomment-502707878))

@scristalli The impediment for [#121](https://github.com/llorllale/cactoos-matchers/issues/121) was registered successfully by @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0pdd** [comment]
The puzzle `94-45419d52` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#121](https://github.com/llorllale/cactoos-matchers/issues/121) is not in the agenda of @scristalli[/z](https://www.0crat.com/u/scristalli), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @scristalli[/z](https://www.0crat.com/u/scristalli), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#121](https://github.com/llorllale/cactoos-matchers/issues/121) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
