### ISSUE TITLE
Make actual documentation and samples for org.llorllale.cactoos.matchers.Assertion

### ISSUE THREAD

**Issue by humb1t** [llorllale/cactoos-matchers#122]
Working on https://github.com/yegor256/jpeek/pull/321 I found that if you use `Assertion` as described in JavaDoc:
```
 new Assertion(
        "Must throw an exception",
            () -> {
                Main.main(
                    "--sources", Paths.get(".").toString(),
                    "--target", target.toString(),
                    "--metrics", "#%$!"
                );
                return Boolean.TRUE;
            },
            new Throws(
                "Invalid metric name: '#%$!'",
                IllegalArgumentException.class
            )
        ).affirm();
```
it would `WARN` during compilation and fail the build of zerocracy projects as a result.

For me, it's very disappointing and time-consuming to be forced to use `cactoos-matcher` and then spend time figuring out how it should be used.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@humb1t[/z](https://www.0crat.com/u/humb1t) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@humb1t what is the warning? The use of raw types/lack of `<>`? Are you using the latest version?

**Comment by humb1t** [comment]
@llorllale yes, this is a code https://github.com/yegor256/jpeek/pull/321/files
version is ` <version>0.13</version>`

**Comment by llorllale** [comment]
@humb1t issue is solved by *not* using [raw types](https://docs.oracle.com/javase/tutorial/java/generics/rawTypes.html) - use the diamond operator to fix it.

Also this typo has been fixed in the latest release of cactoos-matchers

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#122` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
