### ISSUE TITLE
Required IsFalse matcher.

### ISSUE THREAD

**Issue by zCRUSADERz** [llorllale/cactoos-matchers#124]
I need an `IsFalse` matcher like an existing `IsTrue`.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@zCRUSADERz you can compose matchers:

```java
    new IsNot<>(new IsTrue())
```

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#124` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by zCRUSADERz** [comment]
@llorllale but `IsFalse` looks better.
