### ISSUE TITLE
findbugs should be enabled in qulice

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#13]
We should enable findbugs in qulice, there is no work to do, the build already passes with it currently.

Also there is a useless configuration property in qulice configuration too that could be removed.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@victornoel 

> the build already passes with it currently

Hardly. When you un-comment the thresholds it's failing with the messages shown in #1

**Comment by victornoel** [comment]
@llorllale I'm talking about findbugs, not jacoco, are they related to each other? I simply removed the `exclude` for findbugs and the build passed...

**Comment by llorllale** [comment]
@victornoel right, fixed in 71328dd765df5b8656a5d9ca957c12f5dd26f895, thanks

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#13](https://github.com/llorllale/cactoos-matchers/issues/13), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#13` already assigned to @llorllale, can't assign to @llorllale

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#13](https://github.com/llorllale/cactoos-matchers/issues/13) is now out of scope
