### ISSUE TITLE
Matcher to test timeouts

### ISSUE THREAD

**Issue by llorllale** [llorllale/cactoos-matchers#133]
We need a proper OOP alternative for [`@Test#timeout`](https://junit.org/junit4/javadoc/latest/org/junit/Test.html#timeout()) (JUnit 4) and [`Assertions#assertTimeout`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertTimeout(java.time.Duration,org.junit.jupiter.api.function.Executable)) (JUnit 5). In particular, the latter reads backwards (it doesn't *assert* a timeout - it asserts whether the code executes *before* the timeout).

**Proposal:**

```java
new Assertion<>(
    "runs in 5 seconds max",
    /* some scalar */,
    new RunsInMax(5, TimeUnit.SECONDS)
).affirm();
```

Where `RunsInMax` is a `Matcher<Scalar<T>>` like `Throws`.

`RunsInMax` fails if the scalar under test throws an error, even before the timeout.

I'm open to suggestions for a better name. Maybe `DoesNotExceed(5, TimeUnit.SECONDS)` sounds better?

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/133#issuecomment-506985237))

@llorllale Job [#133](https://github.com/llorllale/cactoos-matchers/issues/133) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#133](https://github.com/llorllale/cactoos-matchers/issues/133) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/efd6d0fa-27df-4d38-861c-4350853ec2cd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@llorllale usually, with `@Test#timeout`, the timeout is expressed on top of another assertion. You don't just test that a function runs in less than a given amount or fails if not.

Don't you think we should have something like this instead:
```java
new Assertion<>(
    "runs in 5 seconds max",
    () -> new TextOf("test"),
    new MatchesBefore(
        new TextIs("test"),
        5, TimeUnit.SECONDS)
).affirm();
```

An alternative would be for `Assertion#affirm` to be called in the `Scalar` maybe.

**Comment by victornoel** [comment]
@0crat wait for ARC answer

**Comment by 0crat** [comment]
> @0crat wait for ARC answer ([here](https://github.com/llorllale/cactoos-matchers/issues/133#issuecomment-513476014))

@victornoel The impediment for [#133](https://github.com/llorllale/cactoos-matchers/issues/133) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
> @0crat wait for ARC answer ([here](https://github.com/llorllale/cactoos-matchers/issues/133#issuecomment-513476014))

@victornoel There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dddff4c1-9156-49e2-a2d9-cf978c5a9655, thread: pool-11-thread-8
org.codehaus.groovy.runtime.ScriptBytecodeAdapter[66] groovy.lang.MissingPropertyException: No such property: issue for class: com.zerocracy.stk.pm.in.impediments.add_waiting_label
```

[0.48.2](https://github.com/zerocracy/farm): CID: [c14f0688-f370-4ed4-ba68-74a01385b4fc](https://www.0crat.com/footprint/C63314D6Z/c14f0688-f370-4ed4-ba68-74a01385b4fc), Type: "Impediment was registered"

**Comment by llorllale** [comment]
@victornoel I would be OK if you invert the order of the arguments in your example:

```java
new Assertion<>(
    "runs in 5 seconds max",
    () -> new TextOf("test"),
    new MatchesBefore(
        5, TimeUnit.SECONDS.
        new TextIs("test")        
    )
).affirm();
```

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by victornoel** [comment]
@0crat wait for #145 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #145 to be merged ([here](https://github.com/llorllale/cactoos-matchers/issues/133#issuecomment-531554039))

@victornoel Job [#133](https://github.com/llorllale/cactoos-matchers/issues/133) is already on hold

**Comment by 0pdd** [comment]
@llorllale the puzzle [#146](https://github.com/llorllale/cactoos-matchers/issues/146) is still not solved.

**Comment by victornoel** [comment]
@llorllale this was merged in #145, can you close the issue?

**Comment by llorllale** [comment]
@victornoel thanks!

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) all `QA`s are on vacation. Please handle that.

**Comment by 0crat** [comment]
The job [#133](https://github.com/llorllale/cactoos-matchers/issues/133) is now out of scope

**Comment by paulodamaso** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/llorllale/cactoos-matchers/issues/133#issuecomment-532206332))

@paulodamaso There is no quality review for [#133](https://github.com/llorllale/cactoos-matchers/issues/133), no performer

**Comment by 0pdd** [comment]
@llorllale the only puzzle [#146](https://github.com/llorllale/cactoos-matchers/issues/146) is solved here.
