### ISSUE TITLE
Mismatches.java:55-57: Convert all the Matcher tests to...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#136]
The puzzle `106-7cce08fb` from #106 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/3a33a272c2df9153ec01aefc2ec32010610129c1/src/main/java/org/llorllale/cactoos/matchers/Mismatches.java#L55-L57

The puzzle was created by Victor Noël on 22-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dddff4c1-9156-49e2-a2d9-cf978c5a9655, thread: pool-470-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.48.2](https://github.com/zerocracy/farm): Issue: llorllale/cactoos-matchers#136, Action: `opened`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dddff4c1-9156-49e2-a2d9-cf978c5a9655, thread: pool-11-thread-5
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "wbs.xml" in "C63314D6Z" in 2min: java.util.concurrent.locks.ReentrantLock@6d09edc9[Locked by thread pool-470-thread-1]
```

[0.48.2](https://github.com/zerocracy/farm): CID: [c63d328b-b9e7-45b4-9e6e-6d6bcac9034d](https://www.0crat.com/footprint/C63314D6Z/c63d328b-b9e7-45b4-9e6e-6d6bcac9034d), Type: "Add job to WBS"

**Comment by 0pdd** [comment]
The puzzle `106-7cce08fb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#164](https://github.com/llorllale/cactoos-matchers/issues/164) is still not solved.

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#136` is not assigned, can't get performer
