### ISSUE TITLE
Mismatches.java:58-61: Add extra tests for this class to...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#137]
The puzzle `106-33b58c37` from #106 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/3a33a272c2df9153ec01aefc2ec32010610129c1/src/main/java/org/llorllale/cactoos/matchers/Mismatches.java#L58-L61

The puzzle was created by Victor Noël on 22-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dddff4c1-9156-49e2-a2d9-cf978c5a9655, thread: pool-585-thread-1
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "roles.xml" in "C63314D6Z" in 2min: java.util.concurrent.locks.ReentrantLock@6d09edc9[Locked by thread pool-470-thread-1]
```

[0.48.2](https://github.com/zerocracy/farm): Issue: llorllale/cactoos-matchers#137, Action: `opened`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dddff4c1-9156-49e2-a2d9-cf978c5a9655, thread: pool-11-thread-1
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "wbs.xml" in "C63314D6Z" in 2min: java.util.concurrent.locks.ReentrantLock@6d09edc9[Locked by thread pool-470-thread-1]
```

[0.48.2](https://github.com/zerocracy/farm): CID: [963fc8ed-75a3-4762-9a9e-fe99b331c456](https://www.0crat.com/footprint/C63314D6Z/963fc8ed-75a3-4762-9a9e-fe99b331c456), Type: "Add job to WBS"

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/137#issuecomment-691658640))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#137](https://github.com/llorllale/cactoos-matchers/issues/137) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23137%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/137#issuecomment-761120058))

@victornoel The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#137](https://github.com/llorllale/cactoos-matchers/issues/137), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0pdd** [comment]
The puzzle `106-33b58c37` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#137` is not assigned, can't get performer
