### ISSUE TITLE
Mismatches.java:131-133: Add a description in case the...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#138]
The puzzle `106-02263f65` from #106 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/3a33a272c2df9153ec01aefc2ec32010610129c1/src/main/java/org/llorllale/cactoos/matchers/Mismatches.java#L131-L133

The puzzle was created by Victor Noël on 22-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dddff4c1-9156-49e2-a2d9-cf978c5a9655, thread: pool-588-thread-1
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "roles.xml" in "C63314D6Z" in 2min: java.util.concurrent.locks.ReentrantLock@6d09edc9[Locked by thread pool-470-thread-1]
```

[0.48.2](https://github.com/zerocracy/farm): Issue: llorllale/cactoos-matchers#138, Action: `opened`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dddff4c1-9156-49e2-a2d9-cf978c5a9655, thread: pool-11-thread-3
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "wbs.xml" in "C63314D6Z" in 2min: java.util.concurrent.locks.ReentrantLock@6d09edc9[Locked by thread pool-470-thread-1]
```

[0.48.2](https://github.com/zerocracy/farm): CID: [1d25a3ad-9431-45ff-a1ce-db4b72c5e3c5](https://www.0crat.com/footprint/C63314D6Z/1d25a3ad-9431-45ff-a1ce-db4b72c5e3c5), Type: "Add job to WBS"

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#138](https://github.com/llorllale/cactoos-matchers/issues/138) assigned to @ruca905[/z](https://www.0crat.com/u/ruca905), here is [why](https://www.0crat.com/footprint/C63314D6Z/6c898130-eb30-4f71-b4cf-24d742d38545); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@ruca905 I see you are new around here, welcome. If you have questions don't hesitate to ask here, there are no incorrect questions :) 

And also, if a task seems too much as a starter (like the present one that is not so obvious when it's the first time in this project), don't hesitate to simply refuse it with `@0crat refuse`).

If you are inactive for too long (~10 days) on a task, I may remove it from you, so don't hesitate to ask questions :)

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/llorllale/cactoos-matchers/issues/138#issuecomment-692864366); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/138#issuecomment-699608792))

@victornoel The user @ruca905[/z](https://www.0crat.com/u/ruca905) resigned from [#138](https://github.com/llorllale/cactoos-matchers/issues/138), please stop working. Reason for job resignation: Order was cancelled

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/138#issuecomment-711167004))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#138](https://github.com/llorllale/cactoos-matchers/issues/138) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [17days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @ruca905[/z](https://www.0crat.com/u/ruca905): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23138%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/138#issuecomment-751455547))

@victornoel The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#138](https://github.com/llorllale/cactoos-matchers/issues/138), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#138](https://github.com/llorllale/cactoos-matchers/issues/138) assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), here is [why](https://www.0crat.com/footprint/C63314D6Z/44bf3537-28f3-4f0c-8d00-379ae83f83bf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by baudoliver7** [comment]
@victornoel ping

**Comment by victornoel** [comment]
@baudoliver7 why are you pigging me?

**Comment by baudoliver7** [comment]
PR submitted for this issue.

**Comment by victornoel** [comment]
@baudoliver7 the process is the following:
- job is assigned to DEV (you)
- DEV submits a PR
- PR is assigned to REV (@fabriciofx I believe)
- REV reviews and tells ARC (me) it is good to be merged
- ARC does a final review and merge

Currently we are waiting for REV, I cannot do anything.

**Comment by baudoliver7** [comment]
Ok

**Comment by 0pdd** [comment]
The puzzle `106-02263f65` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@baudoliver7 please make sure you will start all you comments with the name of the user you are referring to:

[see](https://github.com/llorllale/cactoos-matchers/issues/138#issuecomment-756603004)

**Comment by baudoliver7** [comment]
@sereshqua I get it

**Comment by baudoliver7** [comment]
@sereshqua Correction has been done for that

**Comment by sereshqua** [comment]
@0crat quality acceptable
