### ISSUE TITLE
Build broken: error installing jdk

### ISSUE THREAD

**Issue by llorllale** [llorllale/cactoos-matchers#141]
Error:
```install-jdk.sh 2019-07-17

Expected feature release number in range of 9 to 14, but got: 8

The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

Build log: https://travis-ci.org/llorllale/cactoos-matchers/builds/561496203

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#141](https://github.com/llorllale/cactoos-matchers/issues/141) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
You @llorllale[/z](https://www.0crat.com/u/llorllale) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by llorllale** [comment]
Fixed in PR #141

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#141` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#141](https://github.com/llorllale/cactoos-matchers/issues/141) is now out of scope
