### ISSUE TITLE
New ARC

### ISSUE THREAD

**Issue by llorllale** [llorllale/cactoos-matchers#143]
@paulodamaso is the new architect

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#143` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
