### ISSUE TITLE
MatchesBeforeTest.java:73-76: Currently MatchesBefore...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#146]
The puzzle `133-30a4a37a` from #133 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/a7efc9eaf7478a64d70501280e1d6fe968be1a0f/src/test/java/org/llorllale/cactoos/matchers/MatchesBeforeTest.java#L73-L76

The puzzle was created by Victor Noël on 15-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#146](https://github.com/llorllale/cactoos-matchers/issues/146) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#146](https://github.com/llorllale/cactoos-matchers/issues/146) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/fe8b552a-2ff7-402c-88e2-096c0840beca); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/146#issuecomment-653899500))

@victornoel Job [#146](https://github.com/llorllale/cactoos-matchers/issues/146) doesn't exist, can't set role

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#146](https://github.com/llorllale/cactoos-matchers/issues/146) assigned to @englishman[/z](https://www.0crat.com/u/englishman), here is [why](https://www.0crat.com/footprint/C63314D6Z/f7cf3f89-2d22-4cb3-9fef-a05bfe15ce00); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/146#issuecomment-658881763))

@victornoel The user @englishman[/z](https://www.0crat.com/u/englishman) resigned from [#146](https://github.com/llorllale/cactoos-matchers/issues/146), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#146](https://github.com/llorllale/cactoos-matchers/issues/146) assigned to @andreoss[/z](https://www.0crat.com/u/andreoss), here is [why](https://www.0crat.com/footprint/C63314D6Z/ad0d10f7-b456-4f5e-abc6-a260a7086c27); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `133-30a4a37a` has disappeared from the source code, that's why I closed this issue.
