### ISSUE TITLE
Remove the usage of 'org.cactoos.collection.CollectionOf' from the project

### ISSUE THREAD

**Issue by fanifieiev** [llorllale/cactoos-matchers#148]
The class [CollectionOf](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/collection/CollectionOf.java) is planned to be removed from `Cactoos` projects shortly. Replace the usage of that class by appropriate collection implementation.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@fanifieiev Let's first decide and implement it in cactoos, then we update it here

**Comment by victornoel** [comment]
@paulodamaso apparently in cactoos there is a todo (https://github.com/yegor256/cactoos/issues/1261) depending on this task, it would make sense to accept it so that the todo can one day be done with, no?

**Comment by paulodamaso** [comment]
@victornoel Ok, ok

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
The job [#148](https://github.com/llorllale/cactoos-matchers/issues/148) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/502da179-d835-465d-9480-0d2d96b5f987); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #151 to be merged

**Comment by victornoel** [comment]
@fanifieiev it's fixed! I think we can close this issue :)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/148#issuecomment-614247954))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#148](https://github.com/llorllale/cactoos-matchers/issues/148) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23148%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
