### ISSUE TITLE
Rultor integration should be fixed

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#152]
I think that the current rultor file is using very old deprecated settings, see for example cactoos's rultor file for an example of working one: https://github.com/yegor256/cactoos/blob/master/.rultor.yml

In particular the docker image used is different, and also maybe the settings.xml file is incorrect too, seeing the kind of error we get when we try to merge with rultor: https://github.com/llorllale/cactoos-matchers/pull/151#issuecomment-612323879

We should configure rultor in a manner similar to cactoos configuration.

**Comment by victornoel** [comment]
@paulodamaso it seems 0crat missed this, can you look at it?

**Comment by paulodamaso** [comment]
@victornoel Let me do this

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/llorllale/cactoos-matchers/issues/152#issuecomment-614108767))

@paulodamaso The job [#152](https://github.com/llorllale/cactoos-matchers/issues/152) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C63314D6Z/fc8b9b08-28db-4555-bb11-8b89b8d8d6f6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@paulodamaso thx!

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
