### ISSUE TITLE
Relocate cactoos' classes and distribute them within cactoos-matchers jar

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#159]
Because cactoos-matchers is used in cactoos and also in other projects using cactoos, we often face conflict between the available classes in the classpath and those expected by a given version of cactoos-matchers (see the whole story with #148 and https://github.com/yegor256/cactoos/issues/1252#issuecomment-561467663 for example).

To avoid any undesired surprises, let's use the maven shade plugin to relocate the cactoos' classes under the `org.llorllale.cactoos.shaded.org.cactoos....`

See also https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html.

**Comment by victornoel** [comment]
@0crat in

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/159#issuecomment-691672439))

@llorllale You @llorllale[/z](https://www.0crat.com/u/llorllale) need to have one of these roles in order to do "Add job to WBS": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/159#issuecomment-691677260))

@victornoel Job [#159](https://github.com/llorllale/cactoos-matchers/issues/159) is already in scope

**Comment by andreoss** [comment]
@victornoel @llorllale More likely it was already discussed, but why not merge `cactoos` and `cactoos-matchers` on source code basis?

**Comment by victornoel** [comment]
@andreoss one reason could be that cactoos-matchers is meant to be a test dependency, while cactoos is meant to be a compile dependency.

**Comment by andreoss** [comment]
@victornoel It could be in `cactoos-tests.jar` than https://maven.apache.org/plugins/maven-jar-plugin/examples/create-test-jar.html

**Comment by victornoel** [comment]
@andreoss I don't think it would be a very good practice because it would mean that we would mix the matchers, the matchers tests and cactoos tests in one place and provide it via a test jar so people using cactoos-tests would get all of that on their classpath…

**Comment by victornoel** [comment]
@andreoss thx!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by victornoel** [comment]
@rultor release, tag is `0.20`

**Comment by victornoel** [comment]
@llorllale @andreoss I just realized that this does not work: for example if you use `StartsWith`, it will expect a `org.llorllale.cactoos.shaded.org.cactoos.Text` but in cactoos it will be a `org.cactoos.Text`! So cactoos does not compile and cannot run tests in practice.

I thought you tested it and it worked @andreoss? Do you know why I am having this problem?

**Comment by victornoel** [comment]
@llorllale @andreoss FYI I've disabled the shade plugin in #201 and will release a new version since 0.20 is broken once it is merged

**Comment by victornoel** [comment]
@rultor release, tag is `0.21`

**Comment by victornoel** [comment]
@rultor release, tag is `0.21`

**Comment by 0pdd** [comment]
@victornoel the puzzle [#220](https://github.com/llorllale/cactoos-matchers/issues/220) is still not solved.

**Comment by 0pdd** [comment]
@victornoel the only puzzle [#220](https://github.com/llorllale/cactoos-matchers/issues/220) is solved here.
