### ISSUE TITLE
TextStartsWith and TextEndsWith

### ISSUE THREAD

**Issue by Vatavuk** [llorllale/cactoos-matchers#16]
Let's create `TextStartsWith` and `TextEndsWith` as an OO laternative to `Matchers.startsWit/Matchers.endsWith`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/16#issuecomment-392548294))

@llorllale Job [#16](https://github.com/llorllale/cactoos-matchers/issues/16) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by dgroup** [comment]
@llorllale, I'm ready to implement this task.
Please assign the ticket to me.

**Comment by llorllale** [comment]
@dgroup let's name them "StartsWith" and "EndsWith" respectively

**Comment by llorllale** [comment]
@0crat assign @dgroup

**Comment by 0crat** [comment]
> @0crat assign @dgroup  ([here](https://github.com/llorllale/cactoos-matchers/issues/16#issuecomment-445461677))

@llorllale The job [#16](https://github.com/llorllale/cactoos-matchers/issues/16) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/1411c309-0f3b-4214-b1a7-765db7de4ef8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@Vatavuk the puzzle [#54](https://github.com/llorllale/cactoos-matchers/issues/54) is still not solved.

**Comment by 0pdd** [comment]
@Vatavuk the only puzzle [#54](https://github.com/llorllale/cactoos-matchers/issues/54) is solved here.

**Comment by dgroup** [comment]
@Vatavuk, the pull request was merged.
Can we close the ticket?

**Comment by dgroup** [comment]
@0crat wait as the pull request was merged.

**Comment by Vatavuk** [comment]
@dgroup thanks

**Comment by 0crat** [comment]
> @0crat wait as the pull request was merged. ([here](https://github.com/llorllale/cactoos-matchers/issues/16#issuecomment-448253299))

@dgroup The impediment for [#16](https://github.com/llorllale/cactoos-matchers/issues/16) was registered successfully by @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)
