### ISSUE TITLE
Assertion.java:70-73: Assertion should rely on mismatch...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#160]
The puzzle `67-1f1425d4` from #67 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/4daa27a3020156119f6ad442c46ba90c2053ced3/src/main/java/org/llorllale/cactoos/matchers/Assertion.java#L70-L73

The puzzle was created by @rultor on 09-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) please, pay attention to this issue

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/160#issuecomment-660124180))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#160](https://github.com/llorllale/cactoos-matchers/issues/160), please stop working. Reason for job resignation: Order was cancelled

**Comment by andreoss** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/160#issuecomment-693604422))

@andreoss The user @andreoss[/z](https://www.0crat.com/u/andreoss) resigned from [#160](https://github.com/llorllale/cactoos-matchers/issues/160), please stop working. Reason for job resignation: Order was cancelled

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/160#issuecomment-701664034))

@fabriciofx This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#160](https://github.com/llorllale/cactoos-matchers/issues/160) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [6days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu): User was resigned from the ticket
    * @andreoss[/z](https://www.0crat.com/u/andreoss): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23160%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@fabriciofx are you going to solve this ticket?

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/160#issuecomment-751455459))

@victornoel The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#160](https://github.com/llorllale/cactoos-matchers/issues/160), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0pdd** [comment]
The puzzle `67-1f1425d4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#160` is not assigned, can't get performer
