### ISSUE TITLE
Bump pom dependencies and move to junit 5

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#162]
See also yegor256/cactoos#1411

**Comment by victornoel** [comment]
@0crat assign me

**Comment by victornoel** [comment]
@0crat wait for #155 to be merged first

**Comment by 0crat** [comment]
> @0crat wait for #155 to be merged first ([here](https://github.com/llorllale/cactoos-matchers/issues/162#issuecomment-658059595))

@victornoel Job `gh:llorllale/cactoos-matchers#162` is not assigned, can't get performer

**Comment by victornoel** [comment]
@0crat wait for #155 to be merged first

**Comment by victornoel** [comment]
@0crat wait for #166 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #166 to be merged ([here](https://github.com/llorllale/cactoos-matchers/issues/162#issuecomment-660244153))

@victornoel Job [#162](https://github.com/llorllale/cactoos-matchers/issues/162) is already on hold

**Comment by 0pdd** [comment]
@victornoel the puzzle [#170](https://github.com/llorllale/cactoos-matchers/issues/170) is still not solved.

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/162#issuecomment-689035772))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#162](https://github.com/llorllale/cactoos-matchers/issues/162) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [2mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23162%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat out

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#162` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@victornoel the only puzzle [#170](https://github.com/llorllale/cactoos-matchers/issues/170) is solved here.
