### ISSUE TITLE
Release 0.19

### ISSUE THREAD

**Issue by andreoss** [llorllale/cactoos-matchers#167]
In order to complete #148 & https://github.com/yegor256/cactoos/issues/1261

**Comment by victornoel** [comment]
@rultor release tag is 0.19

**Comment by victornoel** [comment]
@rultor release, tag=`0.19`

**Comment by victornoel** [comment]
@rultor release, tag=0.19

**Comment by victornoel** [comment]
@rultor release, tag=`0.19`

**Comment by victornoel** [comment]
@andreoss it seems this is all broken, give me some time to solve it, I am new to rultor and I may be missing some things to make it working…

@llorllale @paulodamaso @yegor256 if you have an idea what is wrong here, any help would be welcome :)

**Comment by llorllale** [comment]
@rultor release, tag is `0.19`

**Comment by victornoel** [comment]
@rultor release, tag is `0.19`

**Comment by victornoel** [comment]
@rultor release, tag is `0.19`

**Comment by victornoel** [comment]
@rultor release, tag is `0.19`

**Comment by victornoel** [comment]
@rultor release, tag is `0.19`

**Comment by victornoel** [comment]
GOD, finally :) 

Here you have it @andreoss, feel free to close this issue if it answers your needs!

Thank you again @llorllale for the help

**Comment by andreoss** [comment]
@victornoel @llorllale What was the issue?

**Comment by victornoel** [comment]
@andreoss just that the rultor configuration was very outdated, we had to update it, but it was a bit cryptic so we had to do a lot of try and error. Now it's all good :+1:

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#167` is not assigned, can't get performer
