### ISSUE TITLE
pom.xml:78-81: Migrate existing tests to JUnit 5. It...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#168]
The puzzle `1411-6ab83915` from #1411 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/c9aba9001b89fd2e5f88d3e405bf6dd9b0cb3050/pom.xml#L78-L81

The puzzle was created by Victor Noël on 17-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by victornoel** [comment]
@0pdd superseded by #170
