### ISSUE TITLE
pom.xml:78-81: Migrate existing tests to JUnit 5. It...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#170]
The puzzle `162-6ab83915` from #162 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/310fd5248a600287465dd4d7fbe7ad841c854264/pom.xml#L78-L81

The puzzle was created by Victor Noël on 07-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `162-6ab83915` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)
