### ISSUE TITLE
build.yml:40-42: Add windows-2019 to the test matrix...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#175]
The puzzle `83-98884b90` from #83 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/e03093c0aac77ba8201fb2b68d52fc730aa6ba57/.github/workflows/build.yml#L40-L42

The puzzle was created by @llorllale on 07-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by andreoss** [comment]
@0crat wait for #209

**Comment by 0crat** [comment]
> @0crat wait for #209  ([here](https://github.com/llorllale/cactoos-matchers/issues/175#issuecomment-725749585))

@andreoss Job `gh:llorllale/cactoos-matchers#175` is not assigned, can't get performer

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/175#issuecomment-761100786))

@victornoel The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#175](https://github.com/llorllale/cactoos-matchers/issues/175), please stop working. Reason for job resignation: Order was cancelled

**Comment by victornoel** [comment]
@0crat status

**Comment by 0pdd** [comment]
The puzzle `83-98884b90` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/175#issuecomment-809532621))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#175](https://github.com/llorllale/cactoos-matchers/issues/175) is [in scope](http://www.zerocracy.com/policy.html#14) for 7mon
  * The role is `DEV`
  * The job is assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7) for [16days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23175%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
