### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by llorllale** [llorllale/cactoos-matchers#178]
Let's set up [all-contributors](https://github.com/all-contributors/all-contributors) on our README.

**Comment by llorllale** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/llorllale/cactoos-matchers/issues/178#issuecomment-691675104))

@llorllale You @llorllale[/z](https://www.0crat.com/u/llorllale) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by llorllale** [comment]
@all-contributors add @yegor256 for code

**Comment by llorllale** [comment]
@all-contributors add @yegor256 for code

**Comment by victornoel** [comment]
@0crat assign @llorllale

**Comment by 0crat** [comment]
> @0crat assign @llorllale  ([here](https://github.com/llorllale/cactoos-matchers/issues/178#issuecomment-691677010))

@victornoel The job [#178](https://github.com/llorllale/cactoos-matchers/issues/178) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/f58f19ce-8db7-4e96-9158-c42ae2ea33bf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @llorllale[/z](https://www.0crat.com/u/llorllale) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by llorllale** [comment]
@all-contributors add @llorllale for code

**Comment by llorllale** [comment]
@all-contributors add @yegor256 for code

**Comment by llorllale** [comment]
@all-contributors add @proshin-roman for code

**Comment by llorllale** [comment]
@all-contributors add @dgroup for code

**Comment by llorllale** [comment]
@all-contributors add @andreoss for code

**Comment by llorllale** [comment]
@all-contributors add @victornoel for code

**Comment by llorllale** [comment]
@all-contributors check

**Comment by llorllale** [comment]
@all-contributors add @borysfan for code

**Comment by llorllale** [comment]
@all-contributors add @scristalli for code

**Comment by llorllale** [comment]
@all-contributors add @fanifieiev for code

**Comment by llorllale** [comment]
@all-contributors add @paulodamaso for code

**Comment by llorllale** [comment]
@all-contributors add @Vatavuk for code

**Comment by llorllale** [comment]
@all-contributors add @SharplEr for code

**Comment by llorllale** [comment]
@all-contributors add @vzurauskas for code

**Comment by llorllale** [comment]
@all-contributors add @jsoroka for code

**Comment by llorllale** [comment]
@victornoel done.

Added everyone from the original contributors list except someone named "Nikita Salomatin" - I don't have their GH handle. If someone can locate that person then we will add them.

Also added everyone else from GH's [graph of contributors](https://github.com/llorllale/cactoos-matchers/graphs/contributors)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
