### ISSUE TITLE
IsTrue matcher

### ISSUE THREAD

**Issue by llorllale** [llorllale/cactoos-matchers#19]
Let's create new matcher `IsTrue<Boolean>`.

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/19#issuecomment-393672806))

@llorllale Job [#19](https://github.com/llorllale/cactoos-matchers/issues/19) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by dgroup** [comment]
@llorllale, I'm ok to implement this task.
Could you please assign to me?

**Comment by llorllale** [comment]
@0crat assign @dgroup

**Comment by llorllale** [comment]
@dgroup just implement `IsTrue`. Users should then negate with `IsNot`.

**Comment by 0crat** [comment]
> @0crat assign @dgroup  ([here](https://github.com/llorllale/cactoos-matchers/issues/19#issuecomment-445479011))

@llorllale The job [#19](https://github.com/llorllale/cactoos-matchers/issues/19) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/38093d67-6d3d-4f73-93e8-ea6408a5bb43); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@dgroup thanks!

**Comment by dgroup** [comment]
👍

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#19](https://github.com/llorllale/cactoos-matchers/issues/19) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)
