### ISSUE TITLE
Removing all constructors except the last one in Matcher class creates a lot of copied code

### ISSUE THREAD

**Issue by ruca905** [llorllale/cactoos-matchers#198]
It is created from #165 task
I tried to solve this in #197 PR

**Comment by ruca905** [comment]
@victornoel

**Comment by victornoel** [comment]
@ruca905 @andreoss if there are questions about an issue, let's discuss it directly in the issue, no need to create a new one.

That being said, we can directly discuss this question in the PR itself in this case.

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#198` is not assigned, can't get performer
