### ISSUE TITLE
pom.xml:162-169: This plugin execution was disabled...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#202]
The puzzle `159-5a01dc84` from #159 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/c5404b80adcab48beaa78c6b3b158ec4a2a1713a/pom.xml#L162-L169

The puzzle was created by Victor Noël on 27-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0.0` from issue #159.

**Comment by victornoel** [comment]
@0crat status

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/202#issuecomment-706684539))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#202](https://github.com/llorllale/cactoos-matchers/issues/202) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23202%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/202#issuecomment-706684585))

@victornoel Job [#202](https://github.com/llorllale/cactoos-matchers/issues/202) is already in scope

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/202#issuecomment-761098783))

@victornoel The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#202](https://github.com/llorllale/cactoos-matchers/issues/202), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#202](https://github.com/llorllale/cactoos-matchers/issues/202) assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), here is [why](https://www.0crat.com/footprint/C63314D6Z/706d318e-d21c-44d1-b195-b0c312f77f4b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by baudoliver7** [comment]
@victornoel Let's please discuss about this plugin and the problem in question

**Comment by victornoel** [comment]
@baudoliver7 yes, this is not an easy problem. Basically the original need was introduced in #159. If you have ideas to solve this problem, either using the shade plugin or something else, we can discuss it here: this is more a design job than a programming job. If we find a good idea, we will add a new todo.

Alternatively, do not forget you can also refuse jobs if you don't want to do them.

**Comment by baudoliver7** [comment]
@victornoel This task seems very interesting ! I will try to resolve it :)

**Comment by baudoliver7** [comment]
@victornoel This ticket is assigned to me but doesn't appear in my agenda. Curious :)

**Comment by victornoel** [comment]
@0crat status

**Comment by victornoel** [comment]
@baudoliver7 you can try raising an issue at zerocracy/farm but I would expect you to get ignored there ^^

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/202#issuecomment-770422272))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#202](https://github.com/llorllale/cactoos-matchers/issues/202) is [in scope](http://www.zerocracy.com/policy.html#14) for 4mon
  * The role is `DEV`
  * The job is assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7) for [6days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23202%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by baudoliver7** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/202#issuecomment-772204100))

@baudoliver7 This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#202](https://github.com/llorllale/cactoos-matchers/issues/202) is [in scope](http://www.zerocracy.com/policy.html#14) for 4mon
  * The role is `DEV`
  * The job is assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7) for [8days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23202%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@baudoliver7 how is it going with this? I was thinking (if that's possible) that the maven shade plugin could shade everything BUT the interfaces. Then it should be ok.

**Comment by victornoel** [comment]
@baudoliver7 it seems to be possible with:
```xml
              <relocations>
                <relocation>
                  <pattern>org.cactoos</pattern>
                  <shadedPattern>org.llorllale.cactoos.shaded.org.cactoos</shadedPattern>
                  <excludes>
                    <exclude>org.cactoos.*</exclude>
                  </excludes>
                </relocation>
              </relocations>
```

**Comment by victornoel** [comment]
@baudoliver7 btw even if it doesn't appear in the agenda, it's really assigned to you and you will get the points :)

**Comment by baudoliver7** [comment]
> @baudoliver7 how is it going with this? I was thinking (if that's possible) that the maven shade plugin could shade everything BUT the interfaces. Then it should be ok.

@victornoel I think it's the solution. I will try this.

**Comment by victornoel** [comment]
@baudoliver7 not sure why 0pdd didn't close it itself, so I do it manually, don't hesitate in the future to ask if you need tickets to be closed when the job is done :)

**Comment by baudoliver7** [comment]
@victornoel Got it. Thx :)

**Comment by 0crat** [comment]
Job [#202](https://github.com/llorllale/cactoos-matchers/issues/202) is not in the agenda of @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), can't set title

**Comment by 0crat** [comment]
Job [#202](https://github.com/llorllale/cactoos-matchers/issues/202) is not in the agenda of @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
