### ISSUE TITLE
Simplify TextMatcher to take a Matcher<String>

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#203]
Since `TextMatcher` is meant to work at a lower level of abstraction than the `Matcher<Text>` class it implements, let's make it take a `Matcher<String>` instead of a `Matcher<Text>`.

This will simplify code, behaviour and shouldn't introduce regression.

**Comment by victornoel** [comment]
@0crat assign me

**Comment by victornoel** [comment]
@0crat wait for #204

**Comment by 0crat** [comment]
Job was finished in 47 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/203#issuecomment-858363184))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#203](https://github.com/llorllale/cactoos-matchers/issues/203) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23203%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
