### ISSUE TITLE
IsNumber matcher

### ISSUE THREAD

**Issue by andreoss** [llorllale/cactoos-matchers#207]
There are several classes in cactoos that extend `Number` (`LengthOf`, `DivisionOf`, `AvgOf`, `SumOf`, `NumberOf`, `NumberEnvelope`, `MultiplicationOf`, `MaxOf`, `MinOf`, `Sealed`).

Let's introduce `IsNumber` in order to test them with avoiding calling `intValue()`, `longValue()`, etc on these objects.

**Comment by victornoel** [comment]
@0crat assign @andreoss

**Comment by victornoel** [comment]
@andreoss I see some commits associated to this ticket, but no PR, did you forget to create it?

**Comment by andreoss** [comment]
@victornoel It was merged already https://github.com/llorllale/cactoos-matchers/pull/208

**Comment by victornoel** [comment]
@andreoss ah perfect, next time can you close or ping the bug reporter (or ARC) for the issue to be closed once an issue is fixed? :)

**Comment by victornoel** [comment]
@andreoss also don't hesitate to create an issue in cactoos for starting using this new matcher in the tests then!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@victornoel please make sure problem reported and problem solvers are 2 different persons

**Comment by victornoel** [comment]
@sereshqua yes, we are a bit short in active DEVs but nevertheless, I will try do to so in the future :)

**Comment by sereshqua** [comment]
@0crat quality acceptable
