### ISSUE TITLE
Make Mismatches platform independent

### ISSUE THREAD

**Issue by kokodyn** [llorllale/cactoos-matchers#209]
In Mismatches class there is hardcoded value for new line character. It caues all tests using Mismatches failing on Windows system. 
Details what should be changed:
https://github.com/llorllale/cactoos-matchers/blob/master/src/main/java/org/llorllale/cactoos/matchers/Mismatches.java#L103
Fix is in way.

**Comment by andreoss** [comment]
@kokodyn Related to #175

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
Thank you @kokodyn

**Comment by victornoel** [comment]
@0crat assign @kokodyn

**Comment by kokodyn** [comment]
Hi
Problem fixed in scope of:
https://github.com/llorllale/cactoos-matchers/pull/210

**Comment by 0crat** [comment]
> @0crat assign @kokodyn  ([here](https://github.com/llorllale/cactoos-matchers/issues/209#issuecomment-727241081))

@victornoel Job [#209](https://github.com/llorllale/cactoos-matchers/issues/209) is closed, can't start order
