### ISSUE TITLE
Consistant naming of matcher objects

### ISSUE THREAD

**Issue by andreoss** [llorllale/cactoos-matchers#213]
Follow-up of #207 

The current naming seems inconsistent with the verb part being place at the beginning, at the end and in the middle of an object name. 

Proposal: 
Rename:
  - `IsText` instead of `TextIs`
  - `IsNumber` ... `NumberIs`
  - `HasContent` ... `InputHasContent`
  - `HasString` ... `TextHasString`
  - `HasValue` ... `ScalarHasValue`
  - `Applies` / `IsApplied` ..  `FuncApplies`
In general the verb should be a prefix rather than suffix which 
1) reflects  "is-a" or "has-a" relationship of an object
2) easy to discover via code completion
3) follows the way hamcrest names its classes

**Comment by andreoss** [comment]
@0crat  ping

**Comment by victornoel** [comment]
@andreoss great idea, thx, let's do that.

Let's use `IsApplicable` for the last one

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#213](https://github.com/llorllale/cactoos-matchers/issues/213) assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), here is [why](https://www.0crat.com/footprint/C63314D6Z/4eaa9d39-4f1f-4ca3-85cd-6c1e21ba0cdb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by baudoliver7** [comment]
@victornoel the work has been for 2 days. Just to prevent you. :)

**Comment by victornoel** [comment]
@andreoss this has been merged, if the result is good with you, could you close this ticket?

**Comment by baudoliver7** [comment]
@andreoss ping

**Comment by andreoss** [comment]
Done in #217

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@andreoss please make sure you start all your comments with the name of the user they are referred to, [see](https://github.com/llorllale/cactoos-matchers/issues/213#issuecomment-761610231)

**Comment by sereshqua** [comment]
@0crat quality acceptable
