### ISSUE TITLE
Upgrade to Hamcrest 2.2

### ISSUE THREAD

**Issue by andreoss** [llorllale/cactoos-matchers#214]
As 1.3 branch is no longer supported. Let's move to 2.2

**Comment by victornoel** [comment]
@andreoss  It seems a good idea, thank you

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@victornoel hi! do you know why is this assigned to @fabriciofx, who seems to not longer present in this project.

**Comment by victornoel** [comment]
@sereshqua I discussed with him and he told me he will look into assigned jobs, but I think he is busy, so I will start refusing jobs for him now I think after a delay to give the opportunity to others to take the job :)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)
