### ISSUE TITLE
pom.xml:162-169: This plugin execution was disabled...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#220]
The puzzle `159-5a01dc84` from #159 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/7f14f8ab52077127dfd1dc3da857a8158728eabc/pom.xml#L162-L169

The puzzle was created by Victor Noël on 27-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0.0` from issue #159.

**Comment by victornoel** [comment]
@0crat out

**Comment by victornoel** [comment]
Duplicate of #202 apparently... not sure why

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/llorllale/cactoos-matchers/issues/220#issuecomment-774458125))

@victornoel Job `gh:llorllale/cactoos-matchers#220` is not assigned, can't get performer

**Comment by 0pdd** [comment]
The puzzle `159-5a01dc84` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#220` is not assigned, can't get performer

**Comment by victornoel** [comment]
@rultor release, tag is `0.24`

**Comment by victornoel** [comment]
@rultor release, tag is `0.24`
