### ISSUE TITLE
IsNumber.java:51-52: Introduce a ComparatorMatcher that...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#225]
The puzzle `165-c099c2ad` from #165 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/9b0f9fa20f3ff3a47ccd77a1d4ead7da7ddf558e/src/main/java/org/llorllale/cactoos/matchers/IsNumber.java#L51-L52

The puzzle was created by @baudoliver7 on 17-Jan-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0.0` from issue #165.

**Comment by 0pdd** [comment]
The puzzle `165-c099c2ad` has disappeared from the source code, that's why I closed this issue.

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/225#issuecomment-858362687))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#225](https://github.com/llorllale/cactoos-matchers/issues/225) is [in scope](http://www.zerocracy.com/policy.html#14) for 4mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23225%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/llorllale/cactoos-matchers/issues/225#issuecomment-858764361))

@victornoel Job `gh:llorllale/cactoos-matchers#225` is not assigned, can't get performer
