### ISSUE TITLE
Wrong prefix for TextIs

### ISSUE THREAD

**Issue by paulodamaso** [llorllale/cactoos-matchers#23]
`TextIs.PREFIX` String is wrong: it is "Text with " but should be "Text is ".

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@paulodamaso I'm not sure why you think it's wrong. You get something like the following when texts don't match (ignore that default toString() implementation):

```
Expected: Text with org.llorllale.cactoos.matchers.TextIs$$Lambda$5/1417753194@3c88db62
     but: Text with "abcde"
```
I think "Text with " sounds ok IMHO.

**Comment by paulodamaso** [comment]
@llorllale Actually not:
See the difference "Text with" means that we have a text which have the String in it besides other contents ("This text is abcde" for example). That is not what the class name `TextIs` indicates.

For me, `TextIs` is about the equality of a `String` and a `Text.asString()` values. So that is that behavior that I expect, and the message should say us that or assertion is not correct.

The current message does not says precisely what is the error:
```
        MatcherAssert.assertThat(
            new TextOf("abcde"),
            new TextIs("abcde")
        );
``` 
Asserts true (right), but
```
        MatcherAssert.assertThat(
            new TextOf("abcde"),
            new TextIs("This test is abcde")
        );
``` 
Shows us this message:
```
Expected: Text with org.llorllale.cactoos.matchers.TextIs$$Lambda$2/529116035@77afea7d
     but: Text with "abcde"
```
But "This test is abcde" is a "Text with abcde"

**Comment by llorllale** [comment]
@paulodamaso I see your point

**Comment by llorllale** [comment]
@paulodamaso wanna submit a PR for this one?

**Comment by paulodamaso** [comment]
@llorllale Of course! Take a look at https://github.com/llorllale/cactoos-matchers/pull/24 . Fixed this `toString()` too, take a look.

**Comment by paulodamaso** [comment]
@llorllale I'm closing, it already has been merged

**Comment by 0crat** [comment]
This job is not in scope

**Comment by llorllale** [comment]
@paulodamaos thanks
