### ISSUE TITLE
New matchers to test emptyness of a list or iterable

### ISSUE THREAD

**Issue by baudoliver7** [llorllale/cactoos-matchers#236]
We fill sometimes the need to test if a list, an array or an iterable is empty or not. We can currently do that like this :
```java
new Verifies(array -> array.length > 0)
```
To make it more readable, we can introduce two new matchers :

- `IsEmpty`
- `HasAny`

**Comment by victornoel** [comment]
@baudoliver7 actually, I realized there was already `IsEmptyIterable` and `IsEmptyCollection` from hamcrest. Do you think it could be enough or am I missing something? As for `HasAny`, we could simply use the negation of those above with `IsNot`.

WDYT?

**Comment by baudoliver7** [comment]
@victornoel You are totally right. Let's close this issue.

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#236` is not assigned, can't get performer
