### ISSUE TITLE
Package `org.llorllale.cactoos.matchers` contains all matchers and should be split

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#25]
In order to make the project more clear for understanding i propose to move the matchers to dedicated packages like: 
 -  `org.llorllale.cactoos.matcher.text`
 -  `org.llorllale.cactoos.matcher.collection`
 -  `org.llorllale.cactoos.matcher.iterable`
 -  `org.llorllale.cactoos.matcher.number`
 -  `org.llorllale.cactoos.matcher.io`
 -  `org.llorllale.cactoos.matcher.scalar`
 -  `org.llorllale.cactoos.matcher.text`
 -  `org.llorllale.cactoos.matcher.exception`
 -   etc

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup there are so few matchers that I don't think it's really necessary

**Comment by dgroup** [comment]
For now few, right, but better for the project in the future as it might grow.

**Comment by dgroup** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/25#issuecomment-439624326))

@dgroup This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#25](https://github.com/llorllale/cactoos-matchers/issues/25) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%2325%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by llorllale** [comment]
@dgroup we can create packages when it's needed. Right now the library is small enough that it doesn't make sense.

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#25` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
