### ISSUE TITLE
Matcher to check non-blank text (String, org.cactoos.Text) is required

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#27]

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup `TextNotEmpty`?

**Comment by dgroup** [comment]
Yes, this name is better.

**Comment by llorllale** [comment]
@dgroup and, in keeping with `HasLines` (from #29), let's just call it `NotEmpty`.

**Comment by llorllale** [comment]
@dgroup actually now that i look again at this issue's title, the implementation should be called `NotBlank`. 

`NotEmpty` would imply that it is literally the empty string.

**Comment by dgroup** [comment]
@llorllale, can we merge the request?

**Comment by llorllale** [comment]
@dgroup done in PR #31

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#27` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
