### ISSUE TITLE
@since tag contains invalid/not-actual versions 

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#28]
For now the version is 0.11, however, there are several files with incorrect versions like `1.1`, `1.0`, `0.29`.

**Comment by llorllale** [comment]
@dgroup 

`1.0` is fine for the newest features because we're currently working on `1.0.0-SNAPSHOT`. 

`0.29` is fine as well.

`1.1` is definitely wrong (spotted in `InputHasContentTest`, thanks)

**Comment by llorllale** [comment]
@dgroup fixed `@since` in `InputHasContentTest` in 6258ffe1dcf290c8b488edd1a79f1a4bbbb284b4. Can we close this?

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#28` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
