### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by llorllale** [llorllale/cactoos-matchers#3]
Let's release `0.9` in order to fix yegor256/cactoos#751. We're not releasing a `1.0` yet because #1 is yet to be fixed.

**Comment by llorllale** [comment]
@rultor release, tag is `0.9`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@25988aaf-ee2f-4146-a0f5-fd10756db4a7, thread: AsyncFlush-8
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/llorllale.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1321445420, Type: 'Close job', Author: llorllale
