### ISSUE TITLE
Matcher to check regexp statement in String, o.c.Text.

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#35]
```java
MatcherAssert.assertThat(
       "...",
       new IsMatchedBy("^\\d$")
);
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup please give an example?

**Comment by dgroup** [comment]
@llorllale, updated the description.

**Comment by llorllale** [comment]
@dgroup how about `MatchesRegex`?

**Comment by dgroup** [comment]
Yes, i like this name.

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/35#issuecomment-441821755))

@llorllale Job [#35](https://github.com/llorllale/cactoos-matchers/issues/35) is now in scope, role is `DEV`

**Comment by dgroup** [comment]
@llorllale, i'm ok to implement this also.
Please assign to me.

**Comment by llorllale** [comment]
@0crat assign @dgroup

**Comment by 0crat** [comment]
> @0crat assign @dgroup  ([here](https://github.com/llorllale/cactoos-matchers/issues/35#issuecomment-445554218))

@llorllale The job [#35](https://github.com/llorllale/cactoos-matchers/issues/35) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/5cdf400a-a547-4f7d-91b8-6a422a522824); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@dgroup the puzzle [#60](https://github.com/llorllale/cactoos-matchers/issues/60) is still not solved.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by dgroup** [comment]
@llorllale, closed by mistake, there is one more puzzle found.

**Comment by dgroup** [comment]
@0crat status

**Comment by 0crat** [comment]
GitHub issue is still open, won't close

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/35#issuecomment-446434751))

@dgroup This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#35](https://github.com/llorllale/cactoos-matchers/issues/35) is [in scope](http://www.zerocracy.com/policy.html#14) for 15days
  * The role is `DEV`
  * The job is assigned to @dgroup[/z](https://www.0crat.com/u/dgroup) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @dgroup[/z](https://www.0crat.com/u/dgroup): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%2335%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
@dgroup the only puzzle [#60](https://github.com/llorllale/cactoos-matchers/issues/60) is solved here.

**Comment by dgroup** [comment]
Ok, it's done.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@fc71d736-6328-4ea0-bfd4-3a1b54bc3b5e, thread: AsyncProc-8
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:llorllale/cactoos-matchers#35] declared for identity constraint of element "verbosity".
```

[0.39.7](https://github.com/zerocracy/farm): CID: [06270756-6f65-42ea-b313-f14005d90ee8](https://www.0crat.com/footprint/C63314D6Z/06270756-6f65-42ea-b313-f14005d90ee8), Type: "Close job"
