### ISSUE TITLE
HasValues.java:64-66: Add the opportunity to print the...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#36]
The puzzle `32-2540e9c8` from #32 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/562930cb9156dc1fab2bfaf8116a63f4af79586a/src/main/java/org/llorllale/cactoos/matchers/HasValues.java#L64-L66

The puzzle was created by rultor on 27-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#36](https://github.com/llorllale/cactoos-matchers/issues/36) is now in scope, role is `DEV`

**Comment by dgroup** [comment]
Hi @llorllale ,
Please review the pull request #38

**Comment by dgroup** [comment]
@llorllale , please review the pull request #38

**Comment by 0pdd** [comment]
The puzzle `32-2540e9c8` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#44](https://github.com/llorllale/cactoos-matchers/issues/44) is still not solved.

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#36` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#36](https://github.com/llorllale/cactoos-matchers/issues/36) is now out of scope

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#44](https://github.com/llorllale/cactoos-matchers/issues/44) is solved here.
