### ISSUE TITLE
HasValuesTest.java:63-67: Matcher to test {@link...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#37]
The puzzle `32-59ea1519` from #32 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/562930cb9156dc1fab2bfaf8116a63f4af79586a/src/test/java/org/llorllale/cactoos/matchers/HasValuesTest.java#L63-L67

The puzzle was created by rultor on 27-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#37](https://github.com/llorllale/cactoos-matchers/issues/37) is now in scope, role is `DEV`

**Comment by dgroup** [comment]
Hi @llorllale ,
Please review the pull request #39

**Comment by dgroup** [comment]
@llorllale , please review the pull request #39

**Comment by llorllale** [comment]
@0crat assign @dgroup

**Comment by 0crat** [comment]
> @0crat assign @dgroup  ([here](https://github.com/llorllale/cactoos-matchers/issues/37#issuecomment-444717305))

@llorllale The job [#37](https://github.com/llorllale/cactoos-matchers/issues/37) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/102ee285-93a9-4502-9996-e5ce0089d345); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `32-59ea1519` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#37](https://github.com/llorllale/cactoos-matchers/issues/37) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)
