### ISSUE TITLE
"cactoos" dependency should not be transitive

### ISSUE THREAD

**Issue by llorllale** [llorllale/cactoos-matchers#4]
Otherwise `cactoos` build will fail due to an "undeclared dependency not being used"

**Comment by llorllale** [comment]
Fixed in 6017a540dba41efadf5abd406eb81d06ba7a4ab2

**Comment by llorllale** [comment]
@rultor release, tag is `0.9.1`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@25988aaf-ee2f-4146-a0f5-fd10756db4a7, thread: AsyncFlush-5
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/llorllale.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1321549384, Type: 'Close job', Author: llorllale
