### ISSUE TITLE
When the next release will go-live?

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#41]
Hi @llorllale ,
When do we planning to release the latest features (`v0.12`)?

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by dgroup** [comment]
I would like to have the following issues within the release `0.12`: https://github.com/llorllale/cactoos-matchers/issues/26, https://github.com/llorllale/cactoos-matchers/issues/27, https://github.com/llorllale/cactoos-matchers/issues/32, https://github.com/llorllale/cactoos-matchers/issues/37.
Yes, some of them are under development, but I suppose that soon they will be completed and we can release it.

**Comment by llorllale** [comment]
@dgroup [release in progress](https://github.com/llorllale/cactoos-matchers/issues/26#issuecomment-443924855)

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#41` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
