### ISSUE TITLE
Prohibit assertions with no message in tests

### ISSUE THREAD

**Issue by llorllale** [llorllale/cactoos-matchers#42]
Use of [this specific](https://junit.org/junit4/javadoc/latest/org/hamcrest/MatcherAssert.html#assertThat(T,%20org.hamcrest.Matcher)) overload of `MatcherAssert.assertThat()` should fail the build because providing an adequate assertion message helps a) understand the test better, and b) helps determining why a build failed (if a test fails).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by dgroup** [comment]
@llorllale , [junit 5](https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-names) has functionality which can help to solve the issue with "adequate" assertion message 
```java
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("A special test case")
class DisplayNameDemo {

    @Test
    @DisplayName("Custom test name containing spaces")
    void testWithDisplayNameContainingSpaces() {
    }

    @Test
    @DisplayName("╯°□°）╯")
    void testWithDisplayNameContainingSpecialCharacters() {
    }

    @Test
    @DisplayName("😱")
    void testWithDisplayNameContainingEmoji() {
    }

}
``` 
Is there any plans to migrate from junit `4.8.x` to `5.x`?

**Comment by llorllale** [comment]
@dgroup I have not studied JUnit 5...

**Comment by dgroup** [comment]
Junit 5 also has a way to test exceptions
https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions
```java
    @Test
    void exceptionTesting() {
        Throwable exception = assertThrows(IllegalArgumentException.class, () -> {
            throw new IllegalArgumentException("a message");
        });
        assertEquals("a message", exception.getMessage());
    }
```
I think we need to consider the junit5 features in order to plan the roadmap for current project.
At least avoid implementation of the features which are already implemented within junit5.

**Comment by llorllale** [comment]
@dgroup [these](https://github.com/llorllale/cactoos-matchers#principles are the design principles for `cactoos-matchers`

**Comment by llorllale** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/llorllale/cactoos-matchers/issues/42#issuecomment-445423683))

@llorllale @llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#42](https://github.com/llorllale/cactoos-matchers/issues/42), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/42#issuecomment-445458139))

@llorllale This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#42](https://github.com/llorllale/cactoos-matchers/issues/42) is [in scope](http://www.zerocracy.com/policy.html#14) for 6days
  * The role is `DEV`
  * The job is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale) for [10hr](http://www.zerocracy.com/policy.html#8)
  * @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation!
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @llorllale[/z](https://www.0crat.com/u/llorllale): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%2342%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Job [#42](https://github.com/llorllale/cactoos-matchers/issues/42) is not in the agenda of @llorllale[/z](https://www.0crat.com/u/llorllale), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 10 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#42](https://github.com/llorllale/cactoos-matchers/issues/42) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)
