### ISSUE TITLE
HasValues.java:47-49: HasValuesMatching that accepts...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#44]
The puzzle `36-7ebfe74b` from #36 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/d0497a2a3eb8c3a4a22dfadedd913ad8df69c065/src/main/java/org/llorllale/cactoos/matchers/HasValues.java#L47-L49

The puzzle was created by Yurii Dubinka on 04-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#44](https://github.com/llorllale/cactoos-matchers/issues/44) is now in scope, role is `DEV`

**Comment by llorllale** [comment]
@0crat assign @dgroup

**Comment by 0crat** [comment]
> @0crat assign @dgroup  ([here](https://github.com/llorllale/cactoos-matchers/issues/44#issuecomment-445406578))

@llorllale The job [#44](https://github.com/llorllale/cactoos-matchers/issues/44) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/a5b7de76-14fd-4a30-a6aa-770c13e21e71); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `36-7ebfe74b` has disappeared from the source code, that's why I closed this issue.

**Comment by dgroup** [comment]
@0crat status.

**Comment by 0crat** [comment]
> @0crat status. ([here](https://github.com/llorllale/cactoos-matchers/issues/44#issuecomment-445416280))

@dgroup Can't understand "status.", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by dgroup** [comment]
@0crat status

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#44](https://github.com/llorllale/cactoos-matchers/issues/44) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)
