### ISSUE TITLE
Provide a way to test the stability/correctness of concurrency tests 

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#46]
During the implementation of https://github.com/yegor256/cactoos/pull/968 I've started to think how to avoid the cases like #22. 
Sometimes the test from #22 is failing, sometimes not and in order to prevent it again we can execute the fragile concurrent test(s) at least 20-50 times which can give us some level of confidence.

For example, [junit 5](https://junit.org/junit5/docs/current/user-guide/#writing-tests-repeated-tests) support such way
```java
@RepeatedTest(10)
void repeatedTest() {
    // ...
}
```
As i understood we are not considering the upgrade to junit5 now, so i've googled a few approaches which may help (but review is required):
 - https://turreta.com/2017/07/15/junit-4-run-test-method-more-than-once/
 - https://stackoverflow.com/questions/1492856/easy-way-of-running-the-same-junit-test-over-and-over

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup check out [`org.cactoos.func.Repeated`](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/func/Repeated.java) and see if it satisfies your needs

**Comment by dgroup** [comment]
I think it will be more than enough in cooperation with [TimedFunc](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/func/TimedFunc.java).

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#46` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
