### ISSUE TITLE
Matchers that take String should also take Text

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#5]
The available `Matcher`s often takes `String`s in their constructor.
They should also support taking `Text`.

This concerns at least:
- `InputHasContent`
- `TextHasString`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/5#issuecomment-388584316))

@llorllale Job [#5](https://github.com/llorllale/cactoos-matchers/issues/5) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#5](https://github.com/llorllale/cactoos-matchers/issues/5) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1361353515); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by Vatavuk** [comment]
@victornoel please close this issue, it was solved in #9

**Comment by Vatavuk** [comment]
@llorllale could you release new version of matchers, I need this functionality for issue https://github.com/yegor256/cactoos-http/issues/48

**Comment by victornoel** [comment]
@Vatavuk great, thanks!

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#5](https://github.com/llorllale/cactoos-matchers/issues/5) is now out of scope

**Comment by llorllale** [comment]
@rultor release, tag is `0.10`

**Comment by Vatavuk** [comment]
@llorllale thanks!

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by elenavolokhova** [comment]
@0crat status

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@018e5afb-436d-4bfb-b1b6-392e6db0f6b4, thread: pool-472-thread-1
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: llorllale/cactoos-matchers#5, Comment: 390725194

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@018e5afb-436d-4bfb-b1b6-392e6db0f6b4, thread: pool-472-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: com.amazonaws.SdkClientException: Unable to execute HTTP request: null
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: llorllale/cactoos-matchers#5, Action: `created`

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/5#issuecomment-390952306))

@elenavolokhova This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#5](https://github.com/llorllale/cactoos-matchers/issues/5) is not in scope
  * The job is waiting quality review verdict by @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) for 20hr
  * @vatavuk[/z](https://www.0crat.com/u/vatavuk) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%235%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
