### ISSUE TITLE
TextMatcherEnvelope.java:39-42: Extends the envelope in...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#54]
The puzzle `16-acf734f9` from #16 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/a35a04cae657ae10804b57117bf4c610fb046519/src/main/java/org/llorllale/cactoos/matchers/TextMatcherEnvelope.java#L39-L42

The puzzle was created by Yurii Dubinka on 08-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat assign @dgroup

**Comment by 0crat** [comment]
> @0crat assign @dgroup  ([here](https://github.com/llorllale/cactoos-matchers/issues/54#issuecomment-445491595))

@llorllale The job [#54](https://github.com/llorllale/cactoos-matchers/issues/54) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/2fbc50c1-59a0-46b6-bda1-3f023ee135a7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by dgroup** [comment]
@llorllale i think this ticket can be closed now.

**Comment by llorllale** [comment]
@dgroup we forgot to remove the puzzle (https://github.com/llorllale/cactoos-matchers/pull/56#issuecomment-446422272)

**Comment by dgroup** [comment]
@llorllale, I propose to remove the puzzle within the #60.
That ticket will close the whole story with startsWith/endsWith and TextBasedEnvelope.

**Comment by 0pdd** [comment]
The puzzle `16-acf734f9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#54](https://github.com/llorllale/cactoos-matchers/issues/54) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)
