### ISSUE TITLE
Incorrect implementation for FuncApplies.describeTo

### ISSUE THREAD

**Issue by victornoel** [llorllale/cactoos-matchers#6]
`FuncApplies.describeTo` refers to `Scalar` instead of `Func`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@victornoel check out c643fd7e64aea6895d5150bd99f8cccb78d2e9fd. Can we close this?

**Comment by victornoel** [comment]
@llorllale perfect, thanks

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@25988aaf-ee2f-4146-a0f5-fd10756db4a7, thread: AsyncFlush-5
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/victornoel.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1322167249, Type: 'Close job', Author: victornoel
