### ISSUE TITLE
MatchesRegexTest.java:72-86: The TextMatcherEnvelope...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#60]
The puzzle `35-b5eec46c` from #35 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/2987486c1ac83b2f4ff82369aa847f3eabb2f518/src/test/java/org/llorllale/cactoos/matchers/MatchesRegexTest.java#L72-L86

The puzzle was created by Yurii Dubinka on 09-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0.0` from issue #35.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#60](https://github.com/llorllale/cactoos-matchers/issues/60) is now in scope, role is `DEV`

**Comment by dgroup** [comment]
@llorllale can you assign it to me? 
I'm ready to help.

**Comment by dgroup** [comment]
@llorllale could you please assign this task to me if you are ok.
The PR also is ready.

**Comment by llorllale** [comment]
@0crat assign @dgroup

**Comment by 0crat** [comment]
> @0crat assign @dgroup  ([here](https://github.com/llorllale/cactoos-matchers/issues/60#issuecomment-447688528))

@llorllale The job [#60](https://github.com/llorllale/cactoos-matchers/issues/60) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/e256a07e-d8a8-4e93-bfa2-6d2b1fa39493); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `35-b5eec46c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#60](https://github.com/llorllale/cactoos-matchers/issues/60) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)
