### ISSUE TITLE
HasLines doesn't explain the failed scenario properly

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#62]
Today I found that `HasLines`
```java
    @Test
    public void test(){
        MatcherAssert.assertThat(
            String.format("l1%nl2"),
            new HasLines("l1", "l3")
        );
    }
```
doesn't explain the failed scenario properly
```java
java.lang.AssertionError: 
Expected: <org.cactoos.text.TextOf@3ab39c39>
     but: <org.cactoos.text.TextOf@2eee9593>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
```
We need to call `text.asString()` instead of `Text.toString()`.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/62#issuecomment-447690910))

@llorllale Job [#62](https://github.com/llorllale/cactoos-matchers/issues/62) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by dgroup** [comment]
@llorllale I'm ok to implement this task.
Please assign to me.

**Comment by llorllale** [comment]
@0crat assign @dgroup

**Comment by 0crat** [comment]
> @0crat assign @dgroup ([here](https://github.com/llorllale/cactoos-matchers/issues/62#issuecomment-449033542))

@llorllale The job [#62](https://github.com/llorllale/cactoos-matchers/issues/62) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/29725078-986f-43b1-8aba-e9ae26a265d9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by dgroup** [comment]
@0crat wait as #63 is raised.

**Comment by 0crat** [comment]
> @0crat wait as #63 is raised. ([here](https://github.com/llorllale/cactoos-matchers/issues/62#issuecomment-449053832))

@dgroup The impediment for [#62](https://github.com/llorllale/cactoos-matchers/issues/62) was registered successfully by @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0crat** [comment]
Job was finished in 11 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#62](https://github.com/llorllale/cactoos-matchers/issues/62) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)
