### ISSUE TITLE
HasEntry matcher to check that map has particular entry

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#65]
Now when i need to write the unit test with `java.util.Map` i have to use something like 
```java
        MatcherAssert.assertThat(
            "The 1st team has expected <team/1st/properties/1st> tag",
            new MapOf<>(...),
            new IsMapContaining<>(
                new IsEqual<>("the key"),
                new IsEqual<>("the value")
            )
        );
```
and it would be more clear if we add a new matcher `HasEntry` like 
```java
       MatcherAssert.assertThat(
            "The 1st team has expected <team/1st/properties/1st> tag",
            new MapOf<>(...),
            new HasEntry<>("the key", "the value")
        );
```
The class may have 3 constructors:
- HasEntry(key, value)
- HasEntry(Map.Entry entry)
- HasEntry(BiFunc<K,V,Boolean, String mismatch explanation))

Let's discuss the possiblity of this feature.

**Comment by llorllale** [comment]
@dgroup sounds good. What if we wanted to check more entries?

**Comment by llorllale** [comment]
@dgroup just one: `HasEntry(Map.Entry... entries)`

**Comment by llorllale** [comment]
@dgroup actually we should just have it accept a single key and value. If users want to check for several, they can wrap several `HasEntry` with [`AllOf`](http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/core/AllOf.html). Let's try this approach and see how it feels.

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/65#issuecomment-451139545))

@llorllale Job [#65](https://github.com/llorllale/cactoos-matchers/issues/65) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#65](https://github.com/llorllale/cactoos-matchers/issues/65) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/836fa963-3d03-4c71-b1e8-fb69bb4ed360); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #105 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #105 to be merged ([here](https://github.com/llorllale/cactoos-matchers/issues/65#issuecomment-479179118))

@victornoel The impediment for [#65](https://github.com/llorllale/cactoos-matchers/issues/65) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
@dgroup the puzzle [#114](https://github.com/llorllale/cactoos-matchers/issues/114) is still not solved.

**Comment by victornoel** [comment]
@dgroup I think this can be closed now, the PR has been merged

**Comment by dgroup** [comment]
@victornoel , thanks

**Comment by 0crat** [comment]
Job [#65](https://github.com/llorllale/cactoos-matchers/issues/65) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#65](https://github.com/llorllale/cactoos-matchers/issues/65) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
@dgroup the only puzzle [#114](https://github.com/llorllale/cactoos-matchers/issues/114) is solved here.
