### ISSUE TITLE
Let's update Copyright notice to 2019.

### ISSUE THREAD

**Issue by fabriciofx** [llorllale/cactoos-matchers#66]
Let's update Copyright notice to 2019.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@fabriciofx see https://github.com/zold-io/java-api/issues/87#issuecomment-450886071

**Comment by llorllale** [comment]
@fabriciofx bumped copyright date in 651c0170f12c83ebf4364e5ffa34f23a14e7ab77

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#66` is not assigned, can't get performer
