### ISSUE TITLE
HasProperties matcher to check that java.util.Properties has particular entry(s)

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#67]
In case of single property
```java
      MatcherAssert.assertThat(
            "The 1st team has expected <team/1st/properties/1st> tag",
            new PropertiesOf<>(...),
            new HasProperties("the key", "the value")
      );
```
In case of multiple property it may looks like
```java
      MatcherAssert.assertThat(
            "The 1st team has expected <team/1st/properties/1st> tag",
            new PropertiesOf<>(...),
            new HasProperties(MapEntry ...entries)
      );
```
Let's discuss the possiblity of this functionality.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup `java.util.Properties` is meant to store strings only, therefore accepting `Map.Entry` args is not required.

I think this should just be `HasProperty`. To specify several, users should wrap in [`AllOf`](http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/core/AllOf.html).

**Comment by dgroup** [comment]
@llorllale, agree

**Comment by 0pdd** [comment]
@dgroup the puzzle [#160](https://github.com/llorllale/cactoos-matchers/issues/160) is still not solved.

**Comment by victornoel** [comment]
@dgroup could you close this issue since it was solved in #154?

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#67` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@dgroup the only puzzle [#160](https://github.com/llorllale/cactoos-matchers/issues/160) is solved here.
