### ISSUE TITLE
NotBlank.java:36-38: NotBlank should be changed to...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#69]
The puzzle `58-21ae45f3` from #58 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/63681b90b3e137fa5986a744a3b5cd0b14dc898e/src/main/java/org/llorllale/cactoos/matchers/NotBlank.java#L36-L38

The puzzle was created by @rultor on 03-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0.0` from issue #58.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#69](https://github.com/llorllale/cactoos-matchers/issues/69) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `58-21ae45f3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#69` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#69](https://github.com/llorllale/cactoos-matchers/issues/69) is now out of scope
