### ISSUE TITLE
Extend AllOf in order to support varargs for Matchers

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#73]
Now, if we want to use the `org.hamcrest.core.AllOf` we have to write something like
```java
new AllOf<>(
    new IterableOf<>(
        new Matcher<>(
            ...
        ),
        new Matcher<>(
            ...
        ),
        new Matcher<>(
            ...
        )
    )
)
```
We can avoid it using `Matchers.allOf(Matcher ...args)`, but its belongs to the lib `hamcrest-all`.
I propose to extend the `AllOf` in order to support the vararg ctor which allows us to avoid instantiation of iterable, and without unnecessary indents, we may write most matchers like:
```java
new AllOf<>(
    new Matcher<>( ... ),
    new Matcher<>( ... ),
    new Matcher<>( ... )
)
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup what do you mean "extend"? You want to create a new class that extends hamcrest's `AllOf`?

**Comment by dgroup** [comment]
@llorllale, yes
```java
/**
 * ...
 */
public final class AllOf<T> extends org.hamcrest.core.AllOf<T> {
    /**
     * ...
     */
    public AllOf(final Matcher<? super T> ... matchers) {
        super(new IterableOf<>(matchers));
    }
}
```
Also we can write the own implementation of `Matcher`, but i think it will be overengineering for this case.

**Comment by llorllale** [comment]
@dgroup I think it would be better to provide a PR for hamcrest.

**Comment by dgroup** [comment]
@llorllale , initially the issue raised because i through
1. They already give this feature as `Matchers.allOf(...)` and available with `hamcrest-all`.
2. They promoting the usage of matchers through static methods annotated as `@org.hamcrest.Factory`, thus it already implemented, no need to add it to the `hamcrest-core`
3. There were no any releases since 2015 in maven central, so it will take months in order to receive such simple feature, however, recently the've released the 
```xml
    <dependency>
      <groupId>org.hamcrest</groupId>
      <artifactId>hamcrest</artifactId>
      <version>2.1</version>
    </dependency>
```
https://mvnrepository.com/artifact/org.hamcrest/hamcrest/2.1
Will try.

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#73` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
