### ISSUE TITLE
When the release 0.13 will go live?

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#76]
There are a lot of changes happens to project since the last release in December.
I would like to use them in my projects.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup point to the issue you need released

**Comment by llorllale** [comment]
@victornoel @dgroup already on it, see https://github.com/llorllale/cactoos-matchers/issues/18#issuecomment-455584703

**Comment by victornoel** [comment]
@llorllale hehe, too fast for us ;) thanks!

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#76` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
