### ISSUE TITLE
Wrong ctor arg name and javadoc

### ISSUE THREAD

**Issue by Serranya** [llorllale/cactoos-matchers#78]
ScalarHasValue has the following Ctor:

https://github.com/llorllale/cactoos-matchers/blob/040051580f8b2b05ad839150a3683b0fb58caa22/src/main/java/org/llorllale/cactoos/matchers/ScalarHasValue.java#L49-L64

The javadoc speaks about `text` which is wrong. And so does the param in the first Ctor.
The scalar is generic and text is not an appropriate name.

I would suggest a more generic name like `value`.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@serranya[/z](https://www.0crat.com/u/serranya) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@Serranya fixed in 8669cf508ededaccaf7e038e98387623899c5c1f.

**Comment by 0crat** [comment]
This job is not in scope
