### ISSUE TITLE
Move to github actions

### ISSUE THREAD

**Issue by fabriciofx** [llorllale/cactoos-matchers#83]
Let's replace travis with github actions, once this is done, we can continue with also running tests on windows.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@llorllale ping

**Comment by victornoel** [comment]
@fabriciofx can you edit the description to move to github actions instead?

**Comment by fabriciofx** [comment]
@victornoel done!

**Comment by victornoel** [comment]
@fabriciofx the description is still incorrect :)

**Comment by victornoel** [comment]
@0crat in

**Comment by fabriciofx** [comment]
@victornoel how about now?

**Comment by victornoel** [comment]
@fabriciofx lol, the title change was already ok, I was talking about the description of the job to be done, currently it is:
> Let's use Appveyor as CI too, not only Travis. Some erros are detected only Windows OSes.

This doesn't reflect what we want to do

**Comment by fabriciofx** [comment]
@victornoel better?

**Comment by victornoel** [comment]
@fabriciofx haha, yes, I don't why but the wording seems... perfection! :P

thx

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#175](https://github.com/llorllale/cactoos-matchers/issues/175) is still not solved.

**Comment by llorllale** [comment]
@fabriciofx @victornoel PR #174 moved us to GitHub Actions. Pending tests on windows due to OS-specific errors there - see puzzle #175).

**Comment by victornoel** [comment]
@llorllale thank you

**Comment by victornoel** [comment]
@0crat assign @llorllale

**Comment by 0crat** [comment]
> @0crat assign @llorllale  ([here](https://github.com/llorllale/cactoos-matchers/issues/83#issuecomment-688666691))

@victornoel The job [#83](https://github.com/llorllale/cactoos-matchers/issues/83) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/dff4ca73-4974-41fa-acf7-385aa01a8c45); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @llorllale[/z](https://www.0crat.com/u/llorllale) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by llorllale** [comment]
@fabriciofx can we close this?

**Comment by fabriciofx** [comment]
@llorllale yeah! Thanks!

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0pdd** [comment]
@fabriciofx the only puzzle [#175](https://github.com/llorllale/cactoos-matchers/issues/175) is solved here.
