### ISSUE TITLE
Replace use of "@Rule ExpectedException" with new Throws

### ISSUE THREAD

**Issue by fabriciofx** [llorllale/cactoos-matchers#85]
There is some place still using `@Rule ExpectedException`. So, let's replace them with `Throws`.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/85#issuecomment-456236720))

@llorllale Job [#85](https://github.com/llorllale/cactoos-matchers/issues/85) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#85](https://github.com/llorllale/cactoos-matchers/issues/85) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/57bdf42a-1195-4871-98e5-e3b347b6f37b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #106

**Comment by 0crat** [comment]
> @0crat wait for #106  ([here](https://github.com/llorllale/cactoos-matchers/issues/85#issuecomment-480505722))

@victornoel The impediment for [#85](https://github.com/llorllale/cactoos-matchers/issues/85) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by andreoss** [comment]
@fabriciofx @llorllale This issue is addressed in #155

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@fabriciofx so actually this is already covered by #136 which is in scope

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#85` is not assigned, can't get performer
