### ISSUE TITLE
Assertion calls test twice

### ISSUE THREAD

**Issue by fabriciofx** [llorllale/cactoos-matchers#86]
`Assertion` calls` Scalar<T> test` twice and this cause some troubles, mainly when testing the content of a stream, like:
```
Assertion(
    "The reason if fails",
    new TextOf(new InputOf(...)),
    new TextHasString("tS")
).affirm()
```
because in the first call stream will be closed. So, I think a possible solution is put a `Sticky` decorator on `Scalar<T> test` parameter. @llorllale WDYT?

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@fabriciofx this is a duplicate of #53

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#86` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
