### ISSUE TITLE
Update PR guidelines in PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by fabriciofx** [llorllale/cactoos-matchers#92]
Cactoos project [updated PR guidelines](https://github.com/yegor256/cactoos/commit/b8bf44e4ddbe0b5a9b13e006208327358931c0cd) and I think it would be nice if we do that too. The new rules are:

- You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
- You ran the build locally and it passed
- Title begins with the issue's number, then a short title
- Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
- Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@fabriciofx fixed in 9d3c028c5498a514a4e875a871efe2ddadee3b8f

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#92` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
