### ISSUE TITLE
InputHasContent.java:37-39: Remove checkstyle suppression...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#93]
The puzzle `75-33ff5101` from #75 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/3fadaceff8aee677f840350ae2a46a879d1806a4/src/main/java/org/llorllale/cactoos/matchers/InputHasContent.java#L37-L39

The puzzle was created by @rultor on 27-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0.0` from issue #75.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#93](https://github.com/llorllale/cactoos-matchers/issues/93) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#93](https://github.com/llorllale/cactoos-matchers/issues/93) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/f48b1b41-88b1-4f6e-b617-3854a6449660); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/llorllale/cactoos-matchers/issues/93#issuecomment-483616589))

@Umbrah The user @umbrah[/z](https://www.0crat.com/u/umbrah) resigned from [#93](https://github.com/llorllale/cactoos-matchers/issues/93), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0crat** [comment]
The job [#93](https://github.com/llorllale/cactoos-matchers/issues/93) assigned to @longstone[/z](https://www.0crat.com/u/longstone), here is [why](https://www.0crat.com/footprint/C63314D6Z/3e4b553a-91d8-4098-a178-cb520f4047a3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by longstone** [comment]
@0crat wait - issue https://github.com/teamed/qulice/issues/985 is not resolved right now.

**Comment by 0crat** [comment]
> @0crat wait - issue https://github.com/teamed/qulice/issues/985 is not resolved right now. ([here](https://github.com/llorllale/cactoos-matchers/issues/93#issuecomment-487107054))

@longstone The impediment for [#93](https://github.com/llorllale/cactoos-matchers/issues/93) was registered successfully by @longstone[/z](https://www.0crat.com/u/longstone)

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0pdd** [comment]
The puzzle `75-33ff5101` has disappeared from the source code, that's why I closed this issue.
