### ISSUE TITLE
Update jcabi-parent to 0.49.4 (solves xcop issue)

### ISSUE THREAD

**Issue by fabriciofx** [llorllale/cactoos-matchers#95]
Let's update to new jcabi version (0.49.4) because this new version solves xcop issue on windows.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@fabriciofx done in 013873cfe132cb0f3d17b807951902f182d54e36

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#95` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
