### ISSUE TITLE
EndsWithTest.java:40-42: We should also look into banning...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#99]
The puzzle `80-ce342b3c` from #80 has to be resolved: 

https://github.com/llorllale/cactoos-matchers/blob/95197861bf502180f9c70f0681389119d518237d/src/test/java/org/llorllale/cactoos/matchers/EndsWithTest.java#L40-L42

The puzzle was created by @rultor on 02-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0.0` from issue #80.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#99](https://github.com/llorllale/cactoos-matchers/issues/99) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/474fc2c5-7328-4ab7-8171-ff0d3b22fc75); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat waiting for #101 to be merged

**Comment by 0crat** [comment]
> @0crat waiting for #101 to be merged ([here](https://github.com/llorllale/cactoos-matchers/issues/99#issuecomment-462050857))

@victornoel The impediment for [#99](https://github.com/llorllale/cactoos-matchers/issues/99) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
The puzzle `80-ce342b3c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#99](https://github.com/llorllale/cactoos-matchers/issues/99) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)
